Add MITRE ATT&CK Mappings to current SCBs
cisagov/ScubaGear pull request #1106
Opened 2024-05-18 23:18 UTC by ahuynhMITRE

## 🗣 Description ##

Added MITRE's ATT&CK TTP mappings and links to applicable security control baselines (SCBs) policies matching the format seen in GWS' SCBs

## 💭 Motivation and context ##

This update to the SCBs is required because it provides additional context into the tactics, techniques, and protocols the policies are attempting to harden against. This will also align the M365 SCBs with the GWS SCBs that currently have the mappings.

## 🧪 Testing ##

N/A document change only 

## ✅ Pre-approval checklist ##

- [ ] This PR has an informative and human-readable title.
- [ ] PR targets the correct parent branch (e.g., main or release-name) for merge.
- [ ] Changes are limited to a single goal - *eschew scope creep!*
- [ ] Changes are sized such that they do not touch excessive number of files.
- [ ] *All* future TODOs are captured in issues, which are referenced in code comments.
- [ ] These code changes follow the ScubaGear [content style guide](https://github.com/cisagov/ScubaGear/blob/main/CONTENTSTYLEGUIDE.md).
- [ ] Related issues these changes resolve are linked preferably via [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).
- [ ] All relevant type-of-change labels added.
- [ ] All relevant project fields are set.
- [ ] All relevant repo and/or project documentation updated to reflect these changes.
- [ ] Unit tests added/updated to cover PowerShell and Rego changes.
- [ ] Functional tests added/updated to cover PowerShell and Rego changes.
- [ ] All relevant functional tests passed.
- [ ] All automated checks (e.g., linting, static analysis, unit/smoke tests) passed.

## ✅ Pre-merge checklist ##

- [ ] PR passed smoke test check.
- [ ] Feature branch has been rebased against changes from parent branch, as needed

  Use `Rebase branch` button below or use [this](https://www.digitalocean.com/community/tutorials/how-to-rebase-and-update-a-pull-request) reference to rebase from the command line.
- [ ] Resolved all merge conflicts on branch
- [ ] Notified merge coordinator that PR is ready for merge via comment mention

## ✅ Post-merge checklist ##

- [ ] Feature branch deleted after merge to clean up repository.
- [ ] Verified that all checks pass on parent branch (e.g., main or release-name) after merge.

2024-05-28 17:28 UTC, mitchelbaker-cisa requested changes
Main formatting considerations: 

Bullets should start with the parent technique. If there are sub-techniques then list these as sub bullets for each baseline.

- [T1110: Brute Force](https://attack.mitre.org/techniques/T1110/)
   - [T1110.001: Password Guessing](https://attack.mitre.org/techniques/T1110/001/)
   - [T1110.002: Password Cracking](https://attack.mitre.org/techniques/T1110/002/)
   - [T1110.003: Password Spraying](https://attack.mitre.org/techniques/T1110/003/)

The techniques are formatted as [T1566:Phishing]. Let's add a space after the colon for all, [T1566: Phishing].

For consistency with GWS let's be sure to reference the parent technique for any sub-techniques.

2024-05-28 17:28 UTC, mitchelbaker-cisa commented on PowerShell/ScubaGear/baselines/teams.md
> +  - [T1566.001:Spearphishing Attachment](https://attack.mitre.org/techniques/T1566/001/)
Reference parent technique https://attack.mitre.org/techniques/T1566/

2024-06-13 15:53 UTC, ahuynhMITRE commented
thanks @mitchelbaker-cisa updated the mappings to do the following:

- add in reference parent ttp mapping
- format sub ttp mappings as sub bullets to these parent ttps
- added a space after the ":" for each policy

2024-06-18 20:12 UTC, mitchelbaker-cisa commented on PowerShell/ScubaGear/baselines/aad.md
> +    - [T1556.007:Hybrid Identity](https://attack.mitre.org/techniques/T1556/007/)
```suggestion
    - [T1556.007: Hybrid Identity](https://attack.mitre.org/techniques/T1556/007/)
```

2024-06-18 20:12 UTC, mitchelbaker-cisa commented on PowerShell/ScubaGear/baselines/aad.md
> +  - [T1651:Cloud Administration Command](https://attack.mitre.org/techniques/T1651/)
```suggestion
  - [T1651: Cloud Administration Command](https://attack.mitre.org/techniques/T1651/)
```

2024-06-18 20:13 UTC, mitchelbaker-cisa commented on PowerShell/ScubaGear/baselines/aad.md
> +  - [T1136:Create Account](https://attack.mitre.org/techniques/T1136/)
```suggestion
  - [T1136: Create Account](https://attack.mitre.org/techniques/T1136/)
```

2024-06-18 20:13 UTC, mitchelbaker-cisa commented on PowerShell/ScubaGear/baselines/aad.md
> +  - [T1136:Create Account](https://attack.mitre.org/techniques/T1136/)
```suggestion
  - [T1136: Create Account](https://attack.mitre.org/techniques/T1136/)
```

2024-06-18 20:13 UTC, mitchelbaker-cisa commented on PowerShell/ScubaGear/baselines/aad.md
> +    - [T1136.003:Cloud Account](https://attack.mitre.org/techniques/T1136/003/)
```suggestion
    - [T1136.003: Cloud Account](https://attack.mitre.org/techniques/T1136/003/)
```

2024-06-18 20:13 UTC, mitchelbaker-cisa commented on PowerShell/ScubaGear/baselines/aad.md
> +  - [T1526:Cloud Service Discovery](https://attack.mitre.org/techniques/T1526/)
```suggestion
  - [T1526: Cloud Service Discovery](https://attack.mitre.org/techniques/T1526/)
```

2024-06-18 20:14 UTC, mitchelbaker-cisa commented on PowerShell/ScubaGear/baselines/defender.md
> +  - [T1567 :Exfiltration Over Web Service](https://attack.mitre.org/techniques/T1567/)
```suggestion
  - [T1567: Exfiltration Over Web Service](https://attack.mitre.org/techniques/T1567/)
```

2024-06-18 20:14 UTC, mitchelbaker-cisa commented on PowerShell/ScubaGear/baselines/defender.md
> +  - [T1567:Exfiltration Over Web Service](https://attack.mitre.org/techniques/T1567/)
```suggestion
  - [T1567: Exfiltration Over Web Service](https://attack.mitre.org/techniques/T1567/)
```

2024-06-18 20:15 UTC, mitchelbaker-cisa commented on PowerShell/ScubaGear/baselines/defender.md
> +  - [T1530:Data from Cloud Storage](https://attack.mitre.org/techniques/T1530/)
```suggestion
  - [T1530: Data from Cloud Storage](https://attack.mitre.org/techniques/T1530/)
```

2024-06-18 20:15 UTC, mitchelbaker-cisa commented on PowerShell/ScubaGear/baselines/defender.md
> +  - [T1213:Data from Information Repositories](https://attack.mitre.org/techniques/T1213/)
```suggestion
  - [T1213: Data from Information Repositories](https://attack.mitre.org/techniques/T1213/)
```

2024-06-18 20:16 UTC, mitchelbaker-cisa commented on PowerShell/ScubaGear/baselines/exo.md
> +    - [T1098.002:Additional Email Delegate Permissions](https://attack.mitre.org/techniques/T1098/002/)
```suggestion
    - [T1098.002: Additional Email Delegate Permissions](https://attack.mitre.org/techniques/T1098/002/)
```

2024-06-18 20:17 UTC, mitchelbaker-cisa commented on PowerShell/ScubaGear/baselines/powerbi.md
> +  - [T1048:Exfiltration Over Alternative Protocol](https://attack.mitre.org/techniques/T1048/)
```suggestion
  - [T1048: Exfiltration Over Alternative Protocol](https://attack.mitre.org/techniques/T1048/)
```

2024-06-18 20:17 UTC, mitchelbaker-cisa commented on PowerShell/ScubaGear/baselines/powerbi.md
> +  - [T1567:Exfiltration Over Web Service](https://attack.mitre.org/techniques/T1567/)
```suggestion
  - [T1567: Exfiltration Over Web Service](https://attack.mitre.org/techniques/T1567/)
```

2024-06-18 20:17 UTC, mitchelbaker-cisa commented on PowerShell/ScubaGear/baselines/powerbi.md
> +  - [T1213.002:Sharepoint](https://attack.mitre.org/techniques/T1213/002/)
```suggestion
  - [T1213.002: Sharepoint](https://attack.mitre.org/techniques/T1213/002/)
```

2024-06-18 20:17 UTC, mitchelbaker-cisa commented on PowerShell/ScubaGear/baselines/powerbi.md
> +  - [T1213:Data from Information Repositories](https://attack.mitre.org/techniques/T1213/)
```suggestion
  - [T1213: Data from Information Repositories](https://attack.mitre.org/techniques/T1213/)
```

2024-06-18 20:17 UTC, mitchelbaker-cisa commented on PowerShell/ScubaGear/baselines/powerbi.md
> +  - [T1530:Data from Cloud Storage](https://attack.mitre.org/techniques/T1530/)
```suggestion
  - [T1530: Data from Cloud Storage](https://attack.mitre.org/techniques/T1530/)
```

2024-06-18 20:19 UTC, mitchelbaker-cisa commented on PowerShell/ScubaGear/baselines/teams.md
> +  - [T1189:Drive-by Compromise](https://attack.mitre.org/techniques/T1189/)
```suggestion
  - [T1189: Drive-by Compromise](https://attack.mitre.org/techniques/T1189/)
```

2024-06-18 20:19 UTC, mitchelbaker-cisa commented on PowerShell/ScubaGear/baselines/teams.md
> +  - [T1189:Drive-by Compromise](https://attack.mitre.org/techniques/T1189/)
```suggestion
  - [T1189: Drive-by Compromise](https://attack.mitre.org/techniques/T1189/)
```

2024-06-18 20:19 UTC, mitchelbaker-cisa approved these changes
Thanks Andrew, looks good!

2024-07-01 17:07 UTC, rmoffitt-m approved these changes

2024-07-08 16:52 UTC, ahuynhMITRE commented
@nanda-katikaneni good to merge!

2024-07-09 17:39 UTC, merged