54 cap policy exclusions
cisagov/ScubaGear pull request #111
Opened 2023-01-08 19:46 UTC by ssatyapal123

#  #
Updated AAD Policies 2.1, 2.2, 2.3, 2.4, 2.9, 2.10, & 2.13 to check for conditional access policy exclusions to users, groups, and roles
## 🗣 Description ##
If the conditional access policies contain user, group, or role exclusions, the baseline policy will fail.  This change is the first step towards adding the capability for users to define allowable exclusions to these policies. Most agencies will want to include some exclusions  to these policies. Therefore, the automation script should be enhanced to allow for these exclusions.

## 💭 Motivation and context ##
AzureAD uses conditional access policies to evaluate access requests. These policies may include references to existing users, groups, and roles with both an inclusion and exclusion condition. Currently, the conditional access policies assume that all users, groups, and roles should  to meet the policy baselines. 

## 🧪 Testing ##
I tested the changes using the AAD Rego unit tests. Reviewers can run the AAD unit tests for each policy baseline statement. Some issues I ran into included not having all the necessary Rego policies defined in the AADConfig.rego, e.g., 
    "All" in Cap.Conditions.Users.IncludeGroups
    "All" in Cap.Conditions.Users.IncludeRoles

## ✅ Pre-approval checklist ##

- [ ] This PR has an informative and human-readable title.
- [ ] Changes are limited to a single goal - *eschew scope creep!*
- [ ] *All* future TODOs are captured in issues, which are referenced
      in code comments.
- [ ] All relevant type-of-change labels have been added.
- [ ] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [ ] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [ ] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
- [ ] Tests have been added and/or modified to cover the changes in this PR.
- [ ] All new and existing tests pass.

## ✅ Pre-merge checklist ##

- [ ] Revert dependencies to default branches.
- [ ] Finalize version.

## ✅ Post-merge checklist ##

- [ ] Add a tag or create a release.

2023-03-16 21:45 UTC, adhilto requested changes
- A few comments are minor readability improvements. These are marked with "optional." Do what you will with these.
- The bulk of my comments deal with some inconsistency in how the exclusion keys are named. In the example config file, they are named `Policy2_x`. However, inside the rego, they are `Policy2_1`, **`Policy2_2_1`**, `Policy2_3`, **`Policy2_4_1`**, `Policy2_9`, and `Policy2_10`. This is one change I would like to see addressed. In my commit suggestions, I recommended 2.2 and 2.4 be renamed to match the `Policy2_x` format used in the example config file, though I suppose it could go the other way.

2023-03-16 21:45 UTC, adhilto commented on Rego/AADConfig.rego
> +    UserExclusionsFullyExempt(Cap, "Policy2_2_1") == true
```suggestion
    UserExclusionsFullyExempt(Cap, "Policy2_2") == true
```

Needs to be "Policy2_2" to match the key used in the config file.

2023-03-16 21:45 UTC, adhilto commented on Rego/AADConfig.rego
> +    GroupExclusionsFullyExempt(Cap, "Policy2_2_1") == true
```suggestion
    UserExclusionsFullyExempt(Cap, "Policy2_2") == true
    GroupExclusionsFullyExempt(Cap, "Policy2_2") == true
```

Change to match config file key.

2023-03-16 21:45 UTC, adhilto commented on Rego/AADConfig.rego
> +    GroupExclusionsFullyExempt(Cap, "Policy2_4_1") == true
```suggestion
    GroupExclusionsFullyExempt(Cap, "Policy2_4") == true
```

Change to match config key

2023-03-16 21:45 UTC, adhilto commented on Rego/AADConfig.rego
> +    GroupExclusionsFullyExempt(Cap, "Policy2_4_1") == true
```suggestion
    UserExclusionsFullyExempt(Cap, "Policy2_4") == true
    GroupExclusionsFullyExempt(Cap, "Policy2_4") == true
```

Change to match config key

2023-03-16 21:45 UTC, adhilto commented on Testing/Unit/Rego/AAD/AADConfig2_02_test.rego
> +                 "Policy2_2_1": {
```suggestion
                 "Policy2_2": {
```

2023-03-16 21:45 UTC, adhilto commented on Testing/Unit/Rego/AAD/AADConfig2_02_test.rego
> +                 "Policy2_2_1": {
```suggestion
                 "Policy2_2": {
```

2023-03-17 16:34 UTC, adhilto commented on Rego/AADConfig.rego
> +    AllowedExcludedUsers
Changing all to `Policy2_x_y` would address my concern, thanks

2023-03-17 17:51 UTC, adhilto approved these changes
Thanks for address my feedback, looks great

2023-03-20 17:21 UTC, nanda-katikaneni commented
merge tests passed (note that there are additional policy failures on a given tenant but these new fails are consistent with implemented cap exclusions) -> merging into the main.

2023-03-20 17:22 UTC, merged