Update Azure Active Directoy, Azure AD, and AAD baseline references from to Microsoft Entra equivalent
cisagov/ScubaGear pull request #1176
Opened 2024-06-21 18:38 UTC by ahuynhMITRE

#  #
  

## 🗣 Description ##

Updated Azure Activie Directoy, Azure AD, AAD references in the markdown files including unique IDs and references in other baselines to match the renaming of the M365 product. 

## 💭 Motivation and context ##

This change is required in order to be up to date with how Microsoft references their products. Microsoft renamed Azure Active Directory (Azure AD) to Microsoft Entra ID to communicate the multicloud, multiplatform functionality of the products, alleviate confusion with Windows Server Active Directory, and unify the Microsoft Entra product family.

Closes issue #888 
linked to #921 

## 🧪 Testing ##

check each instance of Azure Active Directoy, Azure AD, and AAD mentioned in the baselines are correctly replaced with their Microsoft Entra equivalent 

## ✅ Pre-approval checklist ##

- [ ] This PR has an informative and human-readable title.
- [ ] PR targets the correct parent branch (e.g., main or release-name) for merge.
- [ ] Changes are limited to a single goal - *eschew scope creep!*
- [ ] Changes are sized such that they do not touch excessive number of files.
- [ ] *All* future TODOs are captured in issues, which are referenced in code comments.
- [ ] These code changes follow the ScubaGear [content style guide](https://github.com/cisagov/ScubaGear/blob/main/CONTENTSTYLEGUIDE.md).
- [ ] Related issues these changes resolve are linked preferably via [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).
- [ ] All relevant type-of-change labels added.
- [ ] All relevant project fields are set.
- [ ] All relevant repo and/or project documentation updated to reflect these changes.
- [ ] Unit tests added/updated to cover PowerShell and Rego changes.
- [ ] Functional tests added/updated to cover PowerShell and Rego changes.
- [ ] All relevant functional tests passed.
- [ ] All automated checks (e.g., linting, static analysis, unit/smoke tests) passed.

## ✅ Pre-merge checklist ##

- [ ] PR passed smoke test check.
- [ ] Feature branch has been rebased against changes from parent branch, as needed

  Use `Rebase branch` button below or use [this](https://www.digitalocean.com/community/tutorials/how-to-rebase-and-update-a-pull-request) reference to rebase from the command line.
- [ ] Resolved all merge conflicts on branch
- [ ] Notified merge coordinator that PR is ready for merge via comment mention

## ✅ Post-merge checklist ##

- [ ] Feature branch deleted after merge to clean up repository.
- [ ] Verified that all checks pass on parent branch (e.g., main or release-name) after merge.

2024-06-21 18:41 UTC, ahuynhMITRE commented
@buidav & @mitchelbaker-cisa for the unique IDs i originally changed MS.AAD to MS.ENTRAID but looking at Microsoft's documentation their prefered acronym replacement for AAD is ME-ID... 

Link listed below.
https://learn.microsoft.com/en-us/entra/fundamentals/new-name

open to changing it to ENTRAID to match the markdown file name and also not sure if the "-" breaks our automation for pulling unique IDs.

2024-06-24 17:51 UTC, ahuynhMITRE commented on PowerShell/ScubaGear/baselines/defender.md
> +          Business, and Microsoft Entra audit records for one year.
for the other products I was trying to use this table listed below as best I could for updating the terminology! Also for the audit records the article linked keeps it just as "Microsoft Entra" in this section:https://learn.microsoft.com/en-us/purview/audit-log-retention-policies?tabs=microsoft-purview-portal#default-audit-log-retention-policy

Updated terminology link:
https://learn.microsoft.com/en-us/entra/fundamentals/new-name#glossary-of-updated-terminology

2024-06-24 22:48 UTC, ahuynhMITRE commented on PowerShell/ScubaGear/baselines/defender.md
> +          Business, and Microsoft Entra audit records for one year.
haha yep... agree with the sentient on being consistent! Tagging in @mitchelbaker-cisa for any input / preference

2024-06-24 23:03 UTC, mitchelbaker-cisa commented on PowerShell/ScubaGear/baselines/defender.md
> +          Business, and Microsoft Entra audit records for one year.
I concur, we should default to `Microsoft Entra ID` since that's the official naming convention.

2024-06-24 23:21 UTC, mitchelbaker-cisa requested changes
Looks good, although we'll need to investigate into the policy identifier changes further.

2024-06-24 23:21 UTC, mitchelbaker-cisa commented on PowerShell/ScubaGear/baselines/entraid.md
> +# CISA M365 Security Configuration Baseline for Entra ID
```suggestion
# CISA M365 Security Configuration Baseline for Microsoft Entra ID
```

2024-06-24 23:21 UTC, mitchelbaker-cisa commented on PowerShell/ScubaGear/baselines/entraid.md
> +6. Review the output field named **OnPremisesImmutableId**. If this field contains a data value, it means that the  user is not cloud-only. If the user is not cloud-only, create a cloud-only account
```suggestion
6. Review the output field named **OnPremisesImmutableId**. If this field contains a data value, it means that the  user is not cloud-only. If the user is not cloud-only, create a cloud-only account for that user, assign the user to their respective roles and then remove the account that is not cloud-only from Microsoft Entra ID.
```

2024-06-24 23:21 UTC, mitchelbaker-cisa commented on PowerShell/ScubaGear/baselines/powerplatform.md
> +restriction. It does not impact Microsoft Entra -based access outside of Power
```suggestion
restriction. It does not impact Microsoft Entra-based access outside of Power
```

Just an extra space here and in a few other places listed under `3. Power Platform Tenant Isolation`

2024-06-24 23:21 UTC, mitchelbaker-cisa commented on PowerShell/ScubaGear/baselines/teams.md
> +    tenant's Microsfot Entra.
```suggestion
    tenant's Microsoft Entra.
```

2024-06-24 23:21 UTC, mitchelbaker-cisa commented on PowerShell/ScubaGear/baselines/teams.md
> +    agency's Microsfot Entra as guest users. These users
```suggestion
    agency's Microsoft Entra as guest users. These users
```

2024-07-11 17:19 UTC, mitchelbaker-cisa approved these changes
Looks good, two small suggestions.

2024-07-11 17:19 UTC, mitchelbaker-cisa commented on PowerShell/ScubaGear/baselines/powerplatform.md
> +using Microsoft Entra -based authentication, such as Office 365 Outlook or
```suggestion
using Microsoft Entra-based authentication, such as Office 365 Outlook or
```

2024-07-11 17:19 UTC, mitchelbaker-cisa commented on PowerShell/ScubaGear/baselines/powerplatform.md
> +even if the user presents valid credentials to the Microsoft Entra -secured data
```suggestion
even if the user presents valid credentials to the Microsoft Entra-secured data
```

2024-07-15 11:41 UTC, ahuynhMITRE commented
@nanda-katikaneni ready to merge

2024-07-19 13:57 UTC, merged