Reworked EXO Unit Tests to use 1 JSON
cisagov/ScubaGear pull request #1292
Opened 2024-08-29 16:04 UTC by dagarwal-mitre

#  #
  

## 🗣 Description ##

Create central JSON config that can be pulled and modified slightly for each unit test
Closing #1111 
## 💭 Motivation and context ##

Reduce copy and paste errors and file size. Reduce the difficulty of writing unit tests and PRs

## 🧪 Testing ##

- [ ] All EXO unit tests pass
- [ ] Unit tests utilize test assertions for debugging
- [ ] RunUnitTests.ps1 passes all the new utility files

## ✅ Pre-approval checklist ##

- [ ] This PR has an informative and human-readable title.
- [ ] PR targets the correct parent branch (e.g., main or release-name) for merge.
- [ ] Changes are limited to a single goal - *eschew scope creep!*
- [ ] Changes are sized such that they do not touch excessive number of files.
- [ ] *All* future TODOs are captured in issues, which are referenced in code comments.
- [ ] These code changes follow the ScubaGear [content style guide](https://github.com/cisagov/ScubaGear/blob/main/CONTENTSTYLEGUIDE.md).
- [ ] Related issues these changes resolve are linked preferably via [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).
- [ ] All relevant type-of-change labels added.
- [ ] All relevant project fields are set.
- [ ] All relevant repo and/or project documentation updated to reflect these changes.
- [ ] Unit tests added/updated to cover PowerShell and Rego changes.
- [ ] Functional tests added/updated to cover PowerShell and Rego changes.
- [ ] All relevant functional tests passed.
- [ ] All automated checks (e.g., linting, static analysis, unit/smoke tests) passed.

## ✅ Pre-merge checklist ##

- [ ] PR passed smoke test check.
- [ ] Feature branch has been rebased against changes from parent branch, as needed

  Use `Rebase branch` button below or use [this](https://www.digitalocean.com/community/tutorials/how-to-rebase-and-update-a-pull-request) reference to rebase from the command line.
- [ ] Resolved all merge conflicts on branch
- [ ] Notified merge coordinator that PR is ready for merge via comment mention

## ✅ Post-merge checklist ##

- [ ] Feature branch deleted after merge to clean up repository.
- [ ] Verified that all checks pass on parent branch (e.g., main or release-name) after merge.

2024-09-05 22:33 UTC, adhilto requested changes
Overall looks great. The one thing I'd like you to change: there were some really long lines that causing Regal warnings. In an effort to keep things clean and follow best practice, I'd recommend breaking those down. I provided a few examples of how you could do this, it should be very straightforward.

2024-09-05 22:33 UTC, adhilto commented on PowerShell/ScubaGear/Testing/Unit/Rego/EXO/EXOConfig_06_test.rego
> +    SharingPolicy1 := json.patch(SharingPolicy, [{"op": "add", "path": "Domains", "value":["*:ContactsSharing", "domain1:CalendarSharingFreeBusyDetail"]}])
I know this is just a warning in Regal not an error, still, I'd recommend breaking up this line to get rid of the "line too long" warning. Something like this should work:
```
SharingPolicy1 := json.patch(SharingPolicy, [{
    "op": "add",
    "path": "Domains",
    "value": ["*:ContactsSharing", "domain1:CalendarSharingFreeBusyDetail"]
}])
```

2024-09-05 22:33 UTC, adhilto commented on PowerShell/ScubaGear/Testing/Unit/Rego/EXO/EXOConfig_06_test.rego
> +    SharingPolicy1 := json.patch(SharingPolicy, [{"op": "add", "path": "Domains", "value":["*:CalendarSharingFreeBusyDetail", "domain1:ContactsSharing"]}])
Again, I'd recommend breaking down this line:
```
SharingPolicy1 := json.patch(SharingPolicy, [{
    "op": "add",
    "path": "Domains",
    "value": ["*:CalendarSharingFreeBusyDetail", "domain1:ContactsSharing"]
}])
```

2024-09-05 22:33 UTC, adhilto commented on PowerShell/ScubaGear/Testing/Unit/Rego/EXO/EXOConfig_04_test.rego
> +    DmarcRecord1 := json.patch(DmarcRecords, [{"op": "add", "path": "rdata", "value": ["v=DMARC1; p=none; mailto:reports@dmarc.cyber.dhs.gov mailto:jsmith@dhs.gov mailto:jsomething@dhs.gov"]}])
Recommend breaking down this long line

2024-09-05 22:33 UTC, adhilto commented on PowerShell/ScubaGear/Testing/Unit/Rego/EXO/EXOConfig_04_test.rego
> +    DmarcRecord1 := json.patch(DmarcRecords, [{"op": "add", "path": "rdata", "value": ["v=DMARC1; mailto:reports@dmarc.cyber.dhs.gov mailto:jsmith@dhs.gov mailto:jsomething@dhs.gov"]}])
Long line

2024-09-05 22:33 UTC, adhilto commented on PowerShell/ScubaGear/Testing/Unit/Rego/EXO/EXOConfig_04_test.rego
> +    DmarcRecord1 := json.patch(DmarcRecords, [{"op": "add", "path": "rdata", "value": ["v=DMARC1; p=reject; pct=100; rua=mailto:reports@wrong.address"]}])
Long line

2024-09-05 22:33 UTC, adhilto commented on PowerShell/ScubaGear/Testing/Unit/Rego/EXO/EXOConfig_04_test.rego
> +    DmarcRecord1 := json.patch(DmarcRecords, [{"op": "add", "path": "rdata", "value": ["v=DMARC1; p=reject; pct=100; rua=mailto:reports@dmarc.cyber.dhs.gov"]}])
Long line

2024-09-05 22:33 UTC, adhilto commented on PowerShell/ScubaGear/Testing/Unit/Rego/EXO/EXOConfig_04_test.rego
> +    DmarcRecord1 := json.patch(DmarcRecords, [{"op": "add", "path": "rdata", "value": ["v=DMARC1; p=reject; pct=100; rua=mailto:reports@dmarc.cyber.dhs.gov, test@exo.com"]}])
Long line

2024-09-05 22:33 UTC, adhilto commented on PowerShell/ScubaGear/Testing/Unit/Rego/EXO/EXOConfig_04_test.rego
> +    DmarcRecord1 := json.patch(DmarcRecords, [{"op": "add", "path": "rdata", "value": ["v=DMARC1; p=reject; pct=100; rua=mailto:reports@dmarc.cyber.dhs.gov, test@test.name ruf=test2@test.name"]}])
Long line

2024-09-05 22:33 UTC, adhilto commented on PowerShell/ScubaGear/Testing/Unit/Rego/EXO/EXOConfig_04_test.rego
> +    DmarcRecord2 := json.patch(DmarcRecords, [{"op": "add", "path": "rdata", "value": ["v=DMARC1; p=reject; pct=100; rua=mailto:reports@dmarc.cyber.dhs.gov"]},
Long line

2024-09-05 22:33 UTC, adhilto commented on PowerShell/ScubaGear/Testing/Unit/Rego/EXO/EXOConfig_04_test.rego
> +    DmarcRecord2 := json.patch(DmarcRecords, [{"op": "add", "path": "rdata", "value": ["v=DMARC1; p=reject; pct=100; rua=mailto:reports@dmarc.cyber.dhs.gov; ruf=test@exo.com"]},
Long line

2024-09-10 16:25 UTC, dagarwal-mitre commented
@nanda-katikaneni this pr is ready to merge

2024-09-11 15:56 UTC, merged