Adding Conditional Access Policy Implementation Instructions to AAD 1.1
cisagov/ScubaGear pull request #1312
Opened 2024-09-10 17:11 UTC by dagarwal-mitre

#  #
  

## 🗣 Description ##

Updated the implementation guide to follow template of other CAP making it easier on user

## 💭 Motivation and context ##

closes #982 

## 🧪 Testing ##

Read the updated verbose, and ensure it is clear and accurate directions

## ✅ Pre-approval checklist ##

- [ ] This PR has an informative and human-readable title.
- [ ] PR targets the correct parent branch (e.g., main or release-name) for merge.
- [ ] Changes are limited to a single goal - *eschew scope creep!*
- [ ] Changes are sized such that they do not touch excessive number of files.
- [ ] *All* future TODOs are captured in issues, which are referenced in code comments.
- [ ] These code changes follow the ScubaGear [content style guide](https://github.com/cisagov/ScubaGear/blob/main/CONTENTSTYLEGUIDE.md).
- [ ] Related issues these changes resolve are linked preferably via [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).
- [ ] All relevant type-of-change labels added.
- [ ] All relevant project fields are set.
- [ ] All relevant repo and/or project documentation updated to reflect these changes.
- [ ] Unit tests added/updated to cover PowerShell and Rego changes.
- [ ] Functional tests added/updated to cover PowerShell and Rego changes.
- [ ] All relevant functional tests passed.
- [ ] All automated checks (e.g., linting, static analysis, unit/smoke tests) passed.

## ✅ Pre-merge checklist ##

- [ ] PR passed smoke test check.
- [ ] Feature branch has been rebased against changes from parent branch, as needed

  Use `Rebase branch` button below or use [this](https://www.digitalocean.com/community/tutorials/how-to-rebase-and-update-a-pull-request) reference to rebase from the command line.
- [ ] Resolved all merge conflicts on branch
- [ ] Notified merge coordinator that PR is ready for merge via comment mention

## ✅ Post-merge checklist ##

- [ ] Feature branch deleted after merge to clean up repository.
- [ ] Verified that all checks pass on parent branch (e.g., main or release-name) after merge.

2024-10-17 18:22 UTC, tkol2022 requested changes
Nice work. I reviewed the hyperlink in step 1 and it works fine. For step 2 I verified that the instruction template is accurate and I added some suggested bold to one of the words that you can simply commit if you agree with it.

2024-10-17 18:22 UTC, tkol2022 commented on PowerShell/ScubaGear/baselines/aad.md
> +  Conditions > Client apps > Configure > Yes > Legacy authentication clients > Select only <b>Exchange ActiveSync clients</b> and <b>Other clients</b>
```suggestion
  Conditions > Client apps > Configure > <b>Yes</b> > Legacy authentication clients > Select only <b>Exchange ActiveSync clients</b> and <b>Other clients</b>
```

2024-10-18 18:55 UTC, ahuynhMITRE approved these changes
no additional comments to this update.

2024-10-22 19:02 UTC, dagarwal-mitre commented
@nanda-katikaneni this PR is ready to merge

2024-11-11 17:32 UTC, tkol2022 approved these changes

2024-11-11 17:32 UTC, tkol2022 commented
@nanda-katikaneni I believe this is ready to go.

2024-11-11 19:09 UTC, merged