Create ScubaGear-Permissions.json
cisagov/ScubaGear pull request #1380
Opened 2024-10-28 21:24 UTC by MichaelHicks-MSFT

#  #
  

## 🗣 Description ##
Permissions file containing current SCuBAGear permissions mapping.

## 💭 Motivation and context ##
Added permissions file to allow centralized management of all SCuBAGear Microsoft Graph permissions.

## 🧪 Testing ##
Testing was conducted across commercial and gcchigh tenants. Created PowerShell code that imported the JSON file and made connections to Microsoft Graph utilizing the permission scopes defined under Permission within the ScubaGearGraphScopes section of the file.

## ✅ Pre-approval checklist ##

- [ ] This PR has an informative and human-readable title.
- [ ] PR targets the correct parent branch (e.g., main or release-name) for merge.
- [ ] Changes are limited to a single goal - *eschew scope creep!*
- [ ] Changes are sized such that they do not touch excessive number of files.
- [ ] *All* future TODOs are captured in issues, which are referenced in code comments.
- [ ] These code changes follow the ScubaGear [content style guide](https://github.com/cisagov/ScubaGear/blob/main/CONTENTSTYLEGUIDE.md).
- [ ] Related issues these changes resolve are linked preferably via [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).
- [ ] All relevant type-of-change labels added.
- [ ] All relevant project fields are set.
- [ ] All relevant repo and/or project documentation updated to reflect these changes.
- [ ] Unit tests added/updated to cover PowerShell and Rego changes.
- [ ] Functional tests added/updated to cover PowerShell and Rego changes.
- [ ] All relevant functional tests passed.
- [ ] All automated checks (e.g., linting, static analysis, unit/smoke tests) passed.

## ✅ Pre-merge checklist ##

- [ ] PR passed smoke test check.
- [ ] Feature branch has been rebased against changes from parent branch, as needed

  Use `Rebase branch` button below or use [this](https://www.digitalocean.com/community/tutorials/how-to-rebase-and-update-a-pull-request) reference to rebase from the command line.
- [ ] Resolved all merge conflicts on branch
- [ ] Notified merge coordinator that PR is ready for merge via comment mention

## ✅ Post-merge checklist ##

- [ ] Feature branch deleted after merge to clean up repository.
- [ ] Verified that all checks pass on parent branch (e.g., main or release-name) after merge.

2024-10-29 18:55 UTC, tkol2022 requested changes
- Can you move the file from the /Connection folder to a new /Permissions folder instead?
- I noticed you removed the ScubaGearSPPermissions node. In the future ScubaGear will have a utility script that helps users register a service principal to run the tool. Is the thought that our new utility script can just filter the GraphCmdLetPermissions node for entries that are of runtype = application and just use that list to create the needed permissions for the service principal in Entra Id?
- We need to add the following REST APIs as entries to the GraphCmdLetPermissions node along with their associated required permissions. Entra Id now includes direct calls to REST APIs without Cmdlets and therefore we need to ensure those permissions are represented.
  - /beta/roleManagement/directory/roleEligibilityScheduleInstances
  - /beta/roleManagement/directory/roleAssignmentScheduleInstances
  - /beta/identityGovernance/privilegedAccess/group/eligibilityScheduleInstances
  - /beta/privilegedAccess/aadGroups/resources

2024-12-10 20:04 UTC, mitchelbaker-cisa commented
Updated leastPermissions and poshModule keys to array type.

2024-12-10 20:19 UTC, mitchelbaker-cisa commented on PowerShell/ScubaGear/Modules/Permissions/ScubaGearPermissions.json
> +        "apiResource": {
> This is a multi-valued field that sometimes is a string and sometimes a dictionary. As such, recommend always representing as a dictionary. For cases where the API resource is the same across all environments, perhaps use key of "all" or "any"? Either that or replicate URI across all keys in supportedEnv for that entry. The bit of duplication seems reasonable to make it easier to parse.

@MichaelHicks-MSFT could you assist with updating all the "apiResource" keys to be of type dictionary? Please see Addam's comment above. I think for API resources which are the same across all environments, we replicate the URI across all keys. If an environment is not supported for the given resource, set it to null. 

```
{
  "moduleCmdlet": "Connect-PnPOnline",
  "apiResource": {
    "commercial": "https://{domain}-admin.sharepoint.com",
    "gcc": "https://{domain}-admin.sharepoint.com",
    "gcchigh": "https://{domain}-admin.sharepoint.us",
    "dod": "https://{domain}-admin.sharepoint.mil.us"
  },
  ...
}
```

2024-12-23 20:34 UTC, mitchelbaker-cisa commented on PowerShell/ScubaGear/Modules/Permissions/ScubaGearPermissions.json
> +        "permissionType": "Application",
`permissionType` to be removed since its no longer used.

2025-01-02 14:46 UTC, MichaelHicks-MSFT commented
Updated permissions file to reflect discussion last week. Unified keys across objects, renamed rolePermissions to spRolePermissions. Created singular objects for connect cmdlets to break out apiResource based on the environment.

2025-01-16 18:47 UTC, mitchelbaker-cisa commented on PowerShell/ScubaGear/Modules/Permissions/ScubaGearPermissions.json
> +        "leastPermissions": ["Sites.FullControl.All"],
A new property was added to indicate noninteractive permissions, `"spRolePermissions": []`. @buidav does that resolve your comment? Or are additional changes needed.

2025-02-06 16:49 UTC, tkol2022 commented
### Testing Instructions for Interactive authentication
The purpose of this set of tests is to exercise the new pieces of code with an interactive login. There will be separate instructions for testing with service principal.

#### Preparation
Download the main branch and run ScubaGear to create a local scuba results json file which will be used later in a comparison. Run with aad, defender and sharepoint. Include the same products when you run the new code in the steps below.

Download https://github.com/MichaelHicks-MSFT/ScubaGear/tree/main to a local folder /PermissionsJSON 

#### Test to ensure Get-ScubaGearPermissions sets up up the correct permissions for ScubaGear to run interactively
Go to Microsoft Graph Powershell in the Entra Id > Enterprise Applications and click on Permissions
Delete the application from the tenant (this way the permissions will be cleaned out and then recreated the next time that ScubaGear is run)
Go to the PermissionsJSON folder and run ScubaGear interactively. Consent to the permissions for the organization (this is important because it allows others on the team to be able to run ScubaGear interactively).
This should create a Scuba results file

Compare this file against the Scuba results file created from the main branch and ensure that there are no differences that would indicate that the new Powershell code changes had any material effect on the items below. Ignore timestamp and ReportUUID differences.

- The provider JSON that gets created
- The results of the Rego tests

If there are differences between the two files, this indicates that the introduction of the Get-ScubaGearPermissions cmdlet may have introduced a bug.

#### Test to ensure Get-ScubaGearPermissions does not generate any permissions errors (e.g. 401)
Examine the Powershell window where the PermissionsJSON branch was executed and note any permissions errors (e.g. "unauthorized")

#### Test to determine if there are any differences in the permissions created in the tenant that require a review
Go to the Entra Id > Enterprise Applications and open the permissions for the Microsoft Graph Powershell app. These are the permissions created by running the PermissionsJSON with the new Get-ScubaGearPermissions cmdlet in the Connect-Tenant code.
Compare the permissions to another tenant for the same app Microsoft Graph Powershell and note any differences

2025-02-10 16:52 UTC, tkol2022 commented
### Test Results for Interactive authentication - E5 tenant

#### Test 1 - Ensure Get-ScubaGearPermissions sets up up the correct permissions for ScubaGear to run interactively
Compared the configuration settings export and policy check results. No difference between the main branch versus this one. Pass.

#### Test 2 - Ensure Get-ScubaGearPermissions does not generate any permissions errors (e.g. 401)
No permissions errors observed in the console. Pass.

#### Test 3 -Determine if there are any differences in the permissions created in the tenant that require a review
Some new permissions that were not there before were requested for the MS Graph Powershell (Microsoft Graph Command Line Tools) service principal. After discussion with the MS team, this is because each of the cmdlets documented in the JSON permissions include the least privileged permission required to execute the respective cmdlet. Pass.

2025-02-10 17:36 UTC, tkol2022 commented
### Test Results for Interactive authentication - G3 tenant

#### Test 1 - Ensure Get-ScubaGearPermissions sets up up the correct permissions for ScubaGear to run interactively
Pass.

#### Test 2 - Ensure Get-ScubaGearPermissions does not generate any permissions errors (e.g. 401)
Pass.

#### Test 3 -Determine if there are any differences in the permissions created in the tenant that require a review
Pass.

2025-02-10 19:34 UTC, tkol2022 commented
### Test Results for Interactive authentication - GCC High tenant

#### Test 1 - Ensure Get-ScubaGearPermissions sets up up the correct permissions for ScubaGear to run interactively
Pass.

#### Test 2 - Ensure Get-ScubaGearPermissions does not generate any permissions errors (e.g. 401)
Pass.

#### Test 3 -Determine if there are any differences in the permissions created in the tenant that require a review
Pass.

2025-02-11 18:00 UTC, tkol2022 commented
Should the cmdlet Get-ScubaGearEntraRedundantPermissions be renamed to Get-ScubaGearEntraMinimumPermissions? hopefully I understood the intent of the function.

![image](https://github.com/user-attachments/assets/c5c23b3c-3c49-4ed5-a233-dad72cd73057)

2025-02-11 20:38 UTC, tkol2022 commented
### Test Results for Non-Interactive authentication - GCC High, E5 and G3 tenants
The tests were performed on all tenant types listed above. I created a brand new application to test with in each tenant and gave it the permissions listed by the Get-ScubaGearEntraRedundantPermissions cmdlet.

#### Test 1 - Ensure that Connect-Tenant in ScubaGear works correctly with non interactive auth and ScubaGear produces the expected output json and policy results
Pass.

#### Test 2 - Ensure Get-ScubaGearPermissions does not generate any permissions errors (e.g. 401)
Pass.

2025-02-11 20:41 UTC, tkol2022 commented
### Testing changes to Invoke-GraphDirectly
The AAD export provider function Invoke-GraphDirectly was tested indirectly by executing ScubaGear against Entra Id in three tenant types. No issues observed.

2025-02-11 21:06 UTC, tkol2022 commented
Tested parameter validation of Get-ScubaGearPermissions and behaves as expected.

![image](https://github.com/user-attachments/assets/c4048d5b-f46c-436c-8f7a-dcc845446ae0)

2025-02-11 21:10 UTC, tkol2022 approved these changes

2025-02-21 21:31 UTC, tkol2022 commented
I was using ScubaGearPermissions.json as a reference for another issue that I'm working on and I noticed we are missing Get-MgBetaDirectoryObject from the file.

2025-02-21 22:50 UTC, MichaelHicks-MSFT commented
> I was using ScubaGearPermissions.json as a reference for another issue that I'm working on and I noticed we are missing Get-MgBetaDirectoryObject from the file.

I will add that to the file.

2025-02-26 18:34 UTC, tkol2022 commented
This PR is being[ recreated with a new branch directly in the ScubaGear repo](https://github.com/cisagov/ScubaGear/pull/1597).

2025-02-26 18:34 UTC, closed without merging