Add the report UUID to the ScubaResults.json filename
cisagov/ScubaGear pull request #1426
Opened 2024-11-14 00:02 UTC by adhilto

#  #
  

## 🗣 Description ##
Add the report UUID to the ScubaResults.json filename.

## 💭 Motivation and context ##
Ensures each results file has a unique file name. Closes https://github.com/cisagov/ScubaGear/issues/1422.

## 🧪 Testing ##
- Ensured PowerShell unit tests pass
- Added new unit tests to cover the case when there are multiple matching ScubaResults*.json files
- Manually tested `Invoke-Scuba`, works as expected
- Manually tested `Invoke-ScubaCached`, works as expected
- Manually tested `Invoke-ScubaCached` where the input folder has one file matching "ScubaResults*.json", "ScubaResults.json", works as expected
- Manually tested `Invoke-ScubaCached` where the input folder has one file matching "ScubaResults*.json", "ScubaResults_{uuid}.json", works as expected
- Manually tested `Invoke-ScubaCached` where the input folder has two file matching "ScubaResults*.json", the most recently created file is used, as expected
- Manually tested `Invoke-Scuba` and `Invoke-ScubaCached` with a non-default `OutPath` parameter
- Manually tested both `Invoke-Scuba` and `Invoke-ScubaCached` with a non-default `OutJsonFileName` parameter

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] PR targets the correct parent branch (e.g., main or release-name) for merge.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] Changes are sized such that they do not touch excessive number of files.
- [x] *All* future TODOs are captured in issues, which are referenced in code comments.
- [x] These code changes follow the ScubaGear [content style guide](https://github.com/cisagov/ScubaGear/blob/main/CONTENTSTYLEGUIDE.md).
- [x] Related issues these changes resolve are linked preferably via [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).
- [x] All relevant type-of-change labels added.
- [x] All relevant project fields are set.
- [x] All relevant repo and/or project documentation updated to reflect these changes.
- [x] Unit tests added/updated to cover PowerShell and Rego changes.
- [x] Functional tests added/updated to cover PowerShell and Rego changes.
- [x] All relevant functional tests passed.
- [x] All automated checks (e.g., linting, static analysis, unit/smoke tests) passed.

## ✅ Pre-merge checklist ##

- [ ] PR passed smoke test check.
- [ ] Feature branch has been rebased against changes from parent branch, as needed

  Use `Rebase branch` button below or use [this](https://www.digitalocean.com/community/tutorials/how-to-rebase-and-update-a-pull-request) reference to rebase from the command line.
- [ ] Resolved all merge conflicts on branch
- [ ] Notified merge coordinator that PR is ready for merge via comment mention
- [ ] Demonstrate changes to the team for questions and comments. 
    (Note: Only required for issues of size `Medium` or larger)

## ✅ Post-merge checklist ##

- [ ] Feature branch deleted after merge to clean up repository.
- [ ] Verified that all checks pass on parent branch (e.g., main or release-name) after merge.

2024-11-20 14:58 UTC, tkol2022 commented
Should we make the NumberOfUUIDCharactersToTruncate and KeepIndividualJson parameters mutually exclusive? I was thinking if you pass KeepIndividualJson then it doesn't make sense to consider the NumberOfUUIDCharactersToTruncate? Should the tool provide an error alerting the user?

If we decide to implement this, we can add this as an enhancement later because I don't feel comfortable making too many changes given the importance of this release.

![image](https://github.com/user-attachments/assets/0999afca-0a1a-44bd-a59c-bc137bc925dc)

2024-11-20 15:28 UTC, tkol2022 commented
We might want to do some data validation on the OutJsonFileName parameter. If you pass "*" as the name, it crashes.
Maybe add a ValidatePattern to the parameter definition in Invoke-Scuba?

```
[Parameter(Mandatory = $false, ParameterSetName = 'Configuration')]
[Parameter(Mandatory = $false, ParameterSetName = 'Report')]
[ValidateNotNullOrEmpty()]
[ValidatePattern('^[a-zA-Z0-9]+$')]
[string]
$OutJsonFileName = [ScubaConfig]::ScubaDefault('DefaultOutJsonFileName')
```

Again this is an enhancement I think we can make in the future but wanted to discuss.

![image](https://github.com/user-attachments/assets/44776b39-7ae0-45ea-adb3-9399ed5cfddd)

2024-11-20 16:42 UTC, tkol2022 commented
I see that we are truncating the filename GUID in multiple places, ConvertTo-ResultsCsv and Merge-JsonOutput resulting in duplicate logic that we have to keep in synch over time. What if we truncate the GUID in a helper function? Is it worth it?

![image](https://github.com/user-attachments/assets/a051f1ac-7ba4-4f09-92b9-4367c7b86d1a)

![image](https://github.com/user-attachments/assets/1832eb66-78dd-470f-84c3-2f0c7356d809)

Also, the Merge-JsonOutput function gets the GUID from the line of code below which gets it from the settings export object, whereas the ConvertTo-ResultsCsv function gets the GUID from a parameter named $Guid. Should they be consistent? Getting the value from the settings export object seems like a roundabout way to get it.

`$ReportUuid = $SettingsExportObject.report_uuid`

2024-11-20 17:44 UTC, tkol2022 commented
### Testing long paths
This section covers testing with some long file names and folder paths. The purpose was so simulate the conditions where the path of the output JSON file exceeds the maximum system limit and triggers our newly added custom error message in the Merge-JsonOutput function. In some cases I am not getting the expected custom defined error message. 

**Case 1: long OutJsonFileName parameter value**
**I am not getting the expected custom error** because the GetFullPath cmdlet is failing before it gets to our custom error message.

`Invoke-Scuba -ProductNames sharepoint -CertificateThumbPrint "93fd41a761f434f12ee8ac3ff771347597435696" -AppID "db791fde-1ff0-493f-be3d-03d9ba6cb087" -Organization "y2zj1.onmicrosoft.com"  -NumberOfUUIDCharactersToTruncate 13 -OutJsonFileName "aB3cD4eF5gH6iJ7kL8mN9oP0qR1sT2uV3wX4yZ5aB6cD7eF8gH9iJ0kL1mN2oP3qR4sT5uV6wX7yZ8aB9cD0eF1gH2iJ3kL4mN5oP6qR7sT8uV9wX0yZ1aB2cD3eF4gH5iJ6kL7mN8oP9qR0sT1uV2wX3yZ4aB5cD6eF7gH8iJ9kL0mN1oP2qR3sT4uV5wX6yZ7aB8cD9eF0gH1iJ2kL3mN4oP5qR6sT7uV8wX9yZ0"`

![image](https://github.com/user-attachments/assets/f641d405-5c9a-44fa-b3c7-11d44142e5d3)

**Case 2: long OutPath parameter value**
**This works as expected** because I get the custom error message in Merge-JsonOutput.

`Invoke-Scuba -ProductNames sharepoint -CertificateThumbPrint "93fd41a761f434f12ee8ac3ff771347597435696" -AppID "db791fde-1ff0-493f-be3d-03d9ba6cb087" -Organization "y2zj1.onmicrosoft.com"  -NumberOfUUIDCharactersToTruncate 13 -OutPath "C:\Users\tkolovos\Downloads\ScubaLongFolder\aB3cD4eF5gH6iJ7kL8mN9oP0qR1sT2uV3wX4yZ5aB6cD7eF8gH9iJ0kL1mN2oP3qR4sT5uV6wX7yZ8aB9cD0eF1gH2iJ3kL4mN5oP6qR7sT8uV9wX0yZ1aB2cD3eF4gH5iJ6kL7mN8oP9qR0sT1uV2wX3yZ4aB5cD6eF7gH8iJ9kL0mN1oP2qR3sT4uV5wX6yZ7aB8cD9eF"`

![image](https://github.com/user-attachments/assets/e86f5e11-f6b9-4766-9a41-81f0745b4b5d)

**Case 3: long OutFolderName parameter value**
**This works as expected** because I get the custom error message in Merge-JsonOutput.

`Invoke-Scuba -ProductNames sharepoint -CertificateThumbPrint "93fd41a761f434f12ee8ac3ff771347597435696" -AppID "db791fde-1ff0-493f-be3d-03d9ba6cb087" -Organization "y2zj1.onmicrosoft.com"  -NumberOfUUIDCharactersToTruncate 13 -OutFolderName "aB3cD4eF5gH6iJ7kL8mN9oP0qR1sT2uV3wX4yZ5aB6cD7eF8gH9iJ0kL1mN2oP3qR4sT5uV6wX7yZ8aB9cD0eF1gH2iJ3kL4mN5oP6qR7sT8uV9wX0yZ1aB2cD3eF4gH5iJ6kL7mN8oP9qR0sT1uV2wX3yZ4aB5cD6eF7gH8iJ9kL0mN1oP2qR3sT4uV5wX6yZ7aB8cD9eF"`

![image](https://github.com/user-attachments/assets/051b15e7-7883-41bb-a3c6-5b93c28bff33)

**Case 4: long OutFolderName parameter value that is exactly 256 characters (under the limit)**
**This works as expected** and it created the json merged in the long output folder.

`Invoke-Scuba -ProductNames sharepoint -CertificateThumbPrint "93fd41a761f434f12ee8ac3ff771347597435696" -AppID "db791fde-1ff0-493f-be3d-03d9ba6cb087" -Organization "y2zj1.onmicrosoft.com"  -NumberOfUUIDCharactersToTruncate 13 -OutFolderName "aB3cD4eF5gH6iJ7kL8mN9oP0qR1sT2uV3wX4yZ5aB6cD7eF8gH9iJ0kL1mN2oP3qR4sT5uV6wX7yZ8aB9cD0eF1gH2iJ3kL4mN5oP6qR7sT8uV9wX0yZ1aB2cD3eF4gH5iJ6kL7"`

![image](https://github.com/user-attachments/assets/8180bcbc-d97c-47eb-a91d-71310637e15a)

**Case 5: long OutFolderName parameter value that is exactly 256 characters (under the limit) but no truncated characters**
**This works as expected** because I get the custom error message since the addition of the full GUID make the path exceed the limit.

`Invoke-Scuba -ProductNames sharepoint -CertificateThumbPrint "93fd41a761f434f12ee8ac3ff771347597435696" -AppID "db791fde-1ff0-493f-be3d-03d9ba6cb087" -Organization "y2zj1.onmicrosoft.com"  -NumberOfUUIDCharactersToTruncate 0 -OutFolderName "aB3cD4eF5gH6iJ7kL8mN9oP0qR1sT2uV3wX4yZ5aB6cD7eF8gH9iJ0kL1mN2oP3qR4sT5uV6wX7yZ8aB9cD0eF1gH2iJ3kL4mN5oP6qR7sT8uV9wX0yZ1aB2cD3eF4gH5iJ6kL7"`

![image](https://github.com/user-attachments/assets/08938842-2cab-4734-b0d5-29bf01a81dac)

2024-11-20 19:09 UTC, adhilto commented
> > We might want to do some data validation on the OutJsonFileName parameter. If you pass "*" as the name, it crashes. Maybe add a ValidatePattern to the parameter definition in Invoke-Scuba?
> > ```
> > [Parameter(Mandatory = $false, ParameterSetName = 'Configuration')]
> > [Parameter(Mandatory = $false, ParameterSetName = 'Report')]
> > [ValidateNotNullOrEmpty()]
> > [ValidatePattern('^[a-zA-Z0-9]+$')]
> > [string]
> > $OutJsonFileName = [ScubaConfig]::ScubaDefault('DefaultOutJsonFileName')
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Again this is an enhancement I think we can make in the future but wanted to discuss.
> 
> Oh we should probably start checking for this for every file name parameter 👀. Will queue up an issue for this for every file name name parameter.
> 
> For this PR adding the validation to `OutJSONFileName` is a low lift.

I agree with adding validation, but I think it's not as trivial to implement as it seems. See https://stackoverflow.com/questions/1976007/what-characters-are-forbidden-in-windows-and-linux-directory-names.

For example, `S{c}u b-a_(R)e%s^ult$s.json` is a completely valid file name. Will anyone actually use all those characters in a file name? I sure hope not, but we shouldn't impose stricter rules than Windows itself imposes. As some less extreme examples, the example regex in your comment wouldn't allow names such as "Scuba-Results.json", "Scuba_Results.json", and "Scuba Results.json".

TLDR: I think we should save this for a later issue to make sure we think through all the edge cases.

2024-11-20 19:16 UTC, adhilto commented
> I haven't tested this section of the code yet but I have a question. Does this code make the logic windows specific? What types of tweaks will we need in the future if we work on a cross-platform version that doesn't have the same file path limitation coded here?
> 
> ![image](https://private-user-images.githubusercontent.com/107076927/388179294-accb74b3-179d-45f3-b778-9f3ea1befbc1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxMjkxMjAsIm5iZiI6MTczMjEyODgyMCwicGF0aCI6Ii8xMDcwNzY5MjcvMzg4MTc5Mjk0LWFjY2I3NGIzLTE3OWQtNDVmMy1iNzc4LTlmM2VhMWJlZmJjMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMFQxODUzNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMDkxOTk1MmFkMDUxNzJkNmYxYzEwZmVlN2VkY2UxNjU4NTE1ZWFlNDNhYzk2MTQzZmQ3MTVhNDdmZjY2MjAyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.xzImfAQKorP2EgwttqZpbJtmM3AFCuDRuyalTTunGXQ)

Good point, this is a Windows specific limitation. Linux, for example, appears to impose a 255 character limit on file name but no limit on path. https://stackoverflow.com/questions/6571435/limit-on-file-name-length-in-bash

Perhaps a more simple (and more system agnostic) approach would be to simply remove all this added logic and just wrap the `Set-Content` call in a try/catch? Effectively let the system decide what it can or can't handle.

2024-11-20 19:17 UTC, adhilto commented
> > The probability of New-Guid generating an exception is probably negligibly low, but if it does fail and the 0000 value is created as the GUID, won't this cause filename collisions in the downstream file system where the results will be posted if another user happened to get an exception as well? There would be two files, both with the 0000 GUID in the filename. Again the probability is low.
> 
> I've been thinking about this as well. Should we just throw an full exception in this case and stop ScubaGear execution? If `New-Guid` does fail, there most likely is something catastrophically wrong with the underlying system.

I'd be ok with New-Guid failing being a fatal error.

2024-11-20 20:21 UTC, mitchelbaker-cisa commented
> > > The probability of New-Guid generating an exception is probably negligibly low, but if it does fail and the 0000 value is created as the GUID, won't this cause filename collisions in the downstream file system where the results will be posted if another user happened to get an exception as well? There would be two files, both with the 0000 GUID in the filename. Again the probability is low.
> > 
> > 
> > I've been thinking about this as well. Should we just throw an full exception in this case and stop ScubaGear execution? If `New-Guid` does fail, there most likely is something catastrophically wrong with the underlying system.
> 
> I'd be ok with New-Guid failing being a fatal error.

Capturing the two other locations in InvokeSCuBACached where the same guid logic is performed, fatal error should be thrown for these instances as well.

Also, since this try/catch block is repeated 3 times in the orchestrator, does it make sense to break it out as its own utility function? 

![Screenshot (339)](https://github.com/user-attachments/assets/4a39b2ec-2019-4b21-b670-316765ddf254)

2024-11-20 20:32 UTC, adhilto commented
> I see that we are truncating the filename GUID in multiple places, ConvertTo-ResultsCsv and Merge-JsonOutput resulting in duplicate logic that we have to keep in synch over time. What if we truncate the GUID in a helper function? Is it worth it?
> 
> ![image](https://private-user-images.githubusercontent.com/107076927/388185168-a051f1ac-7ba4-4f09-92b9-4367c7b86d1a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxMjkxMjAsIm5iZiI6MTczMjEyODgyMCwicGF0aCI6Ii8xMDcwNzY5MjcvMzg4MTg1MTY4LWEwNTFmMWFjLTdiYTQtNGYwOS05MmI5LTQzNjdjN2I4NmQxYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMFQxODUzNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZTlhNDhlODM2MTM1N2FhNjAyNDc1Zjc5YjI1ZThkMmZjOTY5ZDFkODI5ZDNkNTdkZTE4NDBiMjMwNDZiYWUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.64C3Awh4kvdEl-W10TjY9A2g3a4Bp6ZdpmJHW0LxTMc)
> 
> ![image](https://private-user-images.githubusercontent.com/107076927/388185348-1832eb66-78dd-470f-84c3-2f0c7356d809.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxMjkxMjAsIm5iZiI6MTczMjEyODgyMCwicGF0aCI6Ii8xMDcwNzY5MjcvMzg4MTg1MzQ4LTE4MzJlYjY2LTc4ZGQtNDcwZi04NGMzLTJmMGM3MzU2ZDgwOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMFQxODUzNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03OTMzYzRiNThlYjAwZTBkMThmZTY4MDhjNzVjZDYzMDMwMzQzM2FjNGVmYTQ3ODhlZmQxMzk1OWIxMDVkNTFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.mhpnSgfsLsl0yBeDMuCYeuyebbq--pt4j_vKP4x7wOs)
> 
> Also, the Merge-JsonOutput function gets the GUID from the line of code below which gets it from the settings export object, whereas the ConvertTo-ResultsCsv function gets the GUID from a parameter named $Guid. Should they be consistent? Getting the value from the settings export object seems like a roundabout way to get it.
> 
> `$ReportUuid = $SettingsExportObject.report_uuid`

@tkol2022 I just made this refactor (addresses both comments here).

2024-11-20 20:50 UTC, tkol2022 commented
> > > We might want to do some data validation on the OutJsonFileName parameter. If you pass "*" as the name, it crashes. Maybe add a ValidatePattern to the parameter definition in Invoke-Scuba?
> > > ```
> > > [Parameter(Mandatory = $false, ParameterSetName = 'Configuration')]
> > > [Parameter(Mandatory = $false, ParameterSetName = 'Report')]
> > > [ValidateNotNullOrEmpty()]
> > > [ValidatePattern('^[a-zA-Z0-9]+$')]
> > > [string]
> > > $OutJsonFileName = [ScubaConfig]::ScubaDefault('DefaultOutJsonFileName')
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Again this is an enhancement I think we can make in the future but wanted to discuss.
> > 
> > 
> > Oh we should probably start checking for this for every file name parameter 👀. Will queue up an issue for this for every file name name parameter.
> > For this PR adding the validation to `OutJSONFileName` is a low lift.
> 
> I agree with adding validation, but I think it's not as trivial to implement as it seems. See https://stackoverflow.com/questions/1976007/what-characters-are-forbidden-in-windows-and-linux-directory-names.
> 
> For example, `S{c}u b-a_(R)e%s^ult$s.json` is a completely valid file name. Will anyone actually use all those characters in a file name? I sure hope not, but we shouldn't impose stricter rules than Windows itself imposes. As some less extreme examples, the example regex in your comment wouldn't allow names such as "Scuba-Results.json", "Scuba_Results.json", and "Scuba Results.json".
> 
> TLDR: I think we should save this for a later issue to make sure we think through all the edge cases.

Agree or honestly just let it fail whenever the orchestrator tries to create the file and avoid trying to be too fancy with validation logic, that like you said, might be non trivial. Also keep in mind, we need to think cross-platform.

2024-11-20 20:53 UTC, tkol2022 commented
> > The probability of New-Guid generating an exception is probably negligibly low, but if it does fail and the 0000 value is created as the GUID, won't this cause filename collisions in the downstream file system where the results will be posted if another user happened to get an exception as well? There would be two files, both with the 0000 GUID in the filename. Again the probability is low.
> 
> I've been thinking about this as well. Should we just throw an full exception in this case and stop ScubaGear execution? If `New-Guid` does fail, there most likely is something catastrophically wrong with the underlying system.

Yes, I am not a fan of the 000 GUID. That just seems a little whacky although it will likely work :)

2024-11-20 20:54 UTC, tkol2022 commented
> > I haven't tested this section of the code yet but I have a question. Does this code make the logic windows specific? What types of tweaks will we need in the future if we work on a cross-platform version that doesn't have the same file path limitation coded here?
> > ![image](https://private-user-images.githubusercontent.com/107076927/388179294-accb74b3-179d-45f3-b778-9f3ea1befbc1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxMjkxMjAsIm5iZiI6MTczMjEyODgyMCwicGF0aCI6Ii8xMDcwNzY5MjcvMzg4MTc5Mjk0LWFjY2I3NGIzLTE3OWQtNDVmMy1iNzc4LTlmM2VhMWJlZmJjMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMFQxODUzNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMDkxOTk1MmFkMDUxNzJkNmYxYzEwZmVlN2VkY2UxNjU4NTE1ZWFlNDNhYzk2MTQzZmQ3MTVhNDdmZjY2MjAyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.xzImfAQKorP2EgwttqZpbJtmM3AFCuDRuyalTTunGXQ)
> 
> Good point, this is a Windows specific limitation. Linux, for example, appears to impose a 255 character limit on file name but no limit on path. https://stackoverflow.com/questions/6571435/limit-on-file-name-length-in-bash
> 
> Perhaps a more simple (and more system agnostic) approach would be to simply remove all this added logic and just wrap the `Set-Content` call in a try/catch? Effectively let the system decide what it can or can't handle.

My preference would be to do this (your try/catch idea). Maybe we can catch a specific exception that occurs when the path is too long and then print the custom error message.

2024-11-20 22:03 UTC, mitchelbaker-cisa commented on docs/configuration/parameters.md
> +| Config File | Yes                |
Add the default value for NumberOfUUIDCharactersToTruncate into full_config.yaml or some other sample config file.

2024-11-20 22:03 UTC, mitchelbaker-cisa requested changes
- PS unit tests pass

- Ran `Invoke-SCuBA` against GCC tenant successfully
- Ran `Invoke-SCuBA -KeepIndividualJSON` against GCC tenant successfully, ProviderSettingsExport.json is generated
- Ran `Invoke-SCuBACached` against GCC successfully

- Ran `Invoke-SCuBA` against GCC high tenant successfully 
- Ran `Invoke-SCuBA -KeepIndividualJSON` against GCC high tenant successfully, ProviderSettingsExport.json is generated

Ran `Invoke-SCuBACached` with input that had multiple ScubaResults.json files; pulled from the most recent created
Ran Invoke-SCuBA`/`Invoke-SCuBACached` with non-default OutPath/OutJsonFileName parameters

Tested -NumberOfUUIDCharactersToTruncate in config file; works as expected with various cases (valid positive integer, invalid negative integer) although for invalid cases the error is caught in the generic MergeJson block as opposed to the standard message, "Hey, the integer you provided is not included 0, 13, 18, 36 provided in ValidateSet()."
![Screenshot (341)](https://github.com/user-attachments/assets/676e2b24-1a90-4f92-b68d-b803284b51e2)

2024-11-21 00:31 UTC, mitchelbaker-cisa commented on PowerShell/ScubaGear/Modules/Orchestrator.psm1
> +        # [ValidatePattern('^[a-zA-Z0-9]+$')]
Remove comment, address in future issue 
```suggestion
```

2024-11-21 00:54 UTC, mitchelbaker-cisa commented on PowerShell/ScubaGear/Modules/Orchestrator.psm1
> +        # TODO Stick the GUID within the ScubaConfig object to clean up parameter bloat
Is this comment still relevant? If not remove

2024-11-21 00:54 UTC, mitchelbaker-cisa commented on PowerShell/ScubaGear/Modules/Orchestrator.psm1
> +        # [ValidatePattern('^[a-zA-Z0-9]+$')]
Remove comment, address in future issue 
```suggestion
```

2024-11-21 15:42 UTC, tkol2022 commented
We probably want to remove the explicit inclusion of the stacktrace in the future when Alex's error message handling change goes into effect because this may result in the stacktrace printing twice which would not be user friendly. Thoughts?

![image](https://github.com/user-attachments/assets/876d8a79-5053-4efb-821c-d1c708cd1cb7)

2024-11-21 16:18 UTC, adhilto commented
> We probably want to remove the explicit inclusion of the stacktrace in the future when Alex's error message handling change goes into effect because this may result in the stacktrace printing twice which would not be user friendly. Thoughts?
> 
> ![image](https://private-user-images.githubusercontent.com/107076927/388586659-876d8a79-5053-4efb-821c-d1c708cd1cb7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyMDYxNzcsIm5iZiI6MTczMjIwNTg3NywicGF0aCI6Ii8xMDcwNzY5MjcvMzg4NTg2NjU5LTg3NmQ4YTc5LTUwNTMtNGVmYi04MjFjLWQxYzcwOGNkMWNiNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMVQxNjE3NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hOWE2ZmNiZWMwNjE1YzdhYThhYWY0NTMzNzJmNzczZGY0YmQ3ZjM2M2E0MDc1ODZhNGZiZWMxY2ZlYjM1ZWVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.noBRyjaQMOx41TFP3VJiZOcBGago1yO3dXPsNuSonlY)

Good catch. I put that in for debugging, I hadn't realized I had pushed it.

2024-11-21 18:47 UTC, tkol2022 commented
### Interesting result when Windows has long paths enabled
*Putting this here for future reference.

There is a Windows configuration that allows long paths (i.e. past the default 256 character size limit) when the registry value is configured as per below. My test system has long paths enabled so ScubaGear was able to run fine even past 256 characters.
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem > LongPathsEnabled = 1

The Scuba results json file generated below has a total path length of 284 characters.

![image](https://github.com/user-attachments/assets/b226c699-0e5b-4dac-b927-fdca5076f0fc)

2024-11-21 19:11 UTC, tkol2022 commented
### Results when testing ScubaGear inside a long path
I didn't get a chance to test this specific test case yesterday so I gave it a whirl today. This test simulates how ScubaGear behaves when executing inside a folder that is part of a very long path. The idea was to try and simulate the condition where the creation of the ScubaResults.json file results in an exception due to exceeding the 256 character Windows path limit. The test system has the Windows long paths disabled.

tldr: There is no action for us I don't think. Leave the code as-is. If I am missing something and you want me to re-test, let me know.

**Summary:**
Unfortunately, or fortunately (depending on your sense of humor), I was not able to verify that ScubaGear will catch the exception that occurs when the results json file path exceeds the character limit because I discovered that ScubaGear fails before it even reaches the exception catch logic for the json file. See screenshot for reference. Apparently the log path causes other components to fail first.

ScubaGear was placed into the following folder (194 characters in length):
C:\Users\adminz\Downloads\LongPath\aB3cD4eF5gH6iJ7kL8mN9oP0qR1sT2uV3wX4yZ5aB6cD7eF8gH9iJ0kL1mN2oP3qR4sT5uV6wX7yZ8aB9cD0eF1gH2iJ3kL4mN5oP6qR7sT8uV9wX0yZ1aB2cD3123456789123456789123456789123456789

![image](https://github.com/user-attachments/assets/50a2a096-b9a3-4672-9d4f-48d1209d3542)

2024-11-21 19:51 UTC, tkol2022 commented
### Testing Long Path cases from yesterday (regression)
This is a summary of doing a regression of the long path cases that I ran yesterday. Each test executed below produced a failure in different parts of the code. I'm not if it makes sense to generalize here but I'm thinking that ScubaGear will probably fail in other parts of the code before it arrives at any new logic added in this PR to catch path length errors in Merge-JsonOutput.
I don't think we should change the code at this point. Keep the cases below for future reference.

**Case 1: long OutJsonFileName parameter value**
ScubaGear fails during json reports aggregation.
![image](https://github.com/user-attachments/assets/cb91ba63-cae7-49c2-a5c6-768307038375)


**Case 2: long OutPath parameter value**
ScubaGear fails before it even gets to the results JSON.

![image](https://github.com/user-attachments/assets/72c8cb04-b8d5-49bf-87ff-ccecb687ad80)


**Case 3: long OutFolderName parameter value**
ScubaGear fails before it even gets to the results JSON.

![image](https://github.com/user-attachments/assets/4762b3ee-3425-400d-833c-bd5b5bc17a37)


**Case 4: long OutFolderName parameter value that is exactly 256 characters (under the limit)**
ScubaGear fails before it gets to the results JSON. Depending on the length of the OutFolderName it can fail in multiple places including during the report creation.

![image](https://github.com/user-attachments/assets/f2694401-da7c-45b1-b307-482e054f6c22)

2024-11-21 19:52 UTC, tkol2022 commented
### Regression test summary

- [ ] Test all possible GUID size values for the NumberOfUUIDCharactersToTruncate parameter
- [ ] Test all the cases documented in the PR again 
- [ ] Test the functional test orchestrator
- [ ] Test running scubagear inside a long path without any funny parameters
- [ ] Test the manual run cached

2024-11-21 19:58 UTC, tkol2022 approved these changes
Nice work.

Make sure to run the functional tests action.

2024-11-21 19:58 UTC, tkol2022 commented on docs/configuration/parameters.md
> +**OutJsonFileName** specifies the base file name of the uber output JSON file that is created after a ScubaGear run. This should only be the base file name; the report UUID as well as the extension,
Resolved. Comment was modified.

2024-11-22 17:46 UTC, mitchelbaker-cisa approved these changes

2024-11-22 18:41 UTC, merged