Remove all instances of policy MS.SHAREPOINT4.2v1 due to Microsoft update to custom scripting settings
cisagov/ScubaGear pull request #1447
Opened 2024-12-02 18:39 UTC by ahuynhMITRE

## 🗣 Description ##

Microsoft is making updates to the custom scripting configuration options for Sharepoint and OneDrive. The purpose of this PR is to remove the SCB references to these settings and add the policy, date of removal, and rationale to the removedpolicies.md.

This would be useful because as Microsoft rolls out this update, users of ScubaGear will experience errors as a result of the missing setting. This allows the ScubaGear and the SCBs to be update to date with this setting deprecation.

## 💭 Motivation and context ##

This would be useful because as Microsoft rolls out this update, users of ScubaGear will experience errors as a result of the missing setting. This allows the ScubaGear and the SCBs to be update to date with this setting deprecation.

Closes #1325 
Closes #1399 
Closes #1400 

## 🧪 Testing ##

- [ ] Ensure the following files have updated to remove references to SharePoint policy group 4: custom scripting and its policies
  - [ ] sharepoint.md
  - [ ] SharepointConfig.rego
  - [ ] SharepointConfig_04_test.rego
  - [ ] sharepoint.pnp.testplan.yaml
  - [ ] sharepoint.spo.testplan.yaml

- [ ] Ensure the following files have updated to reference the removal of SharePoint.4.2v1
  - [ ] removedpolicies.md

- [ ] Ensure SharePoint policy group 4: custom scripting and its policies is no longer showing when running scubagear in any of its output files

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] PR targets the correct parent branch (e.g., main or release-name) for merge.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] Changes are sized such that they do not touch excessive number of files.
- [x] *All* future TODOs are captured in issues, which are referenced in code comments.
- [x] These code changes follow the ScubaGear [content style guide](https://github.com/cisagov/ScubaGear/blob/main/CONTENTSTYLEGUIDE.md).
- [x] Related issues these changes resolve are linked preferably via [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).
- [x] All relevant type-of-change labels added.
- [x] All relevant project fields are set.
- [x] All relevant repo and/or project documentation updated to reflect these changes.
- [x] Unit tests added/updated to cover PowerShell and Rego changes.
- [x] Functional tests added/updated to cover PowerShell and Rego changes.
- [x] All relevant functional tests passed.
- [x] All automated checks (e.g., linting, static analysis, unit/smoke tests) passed.

## ✅ Pre-merge checklist ##

- [ ] PR passed smoke test check.
- [ ] Feature branch has been rebased against changes from parent branch, as needed

  Use `Rebase branch` button below or use [this](https://www.digitalocean.com/community/tutorials/how-to-rebase-and-update-a-pull-request) reference to rebase from the command line.
- [ ] Resolved all merge conflicts on branch
- [ ] Notified merge coordinator that PR is ready for merge via comment mention
- [ ] Demonstrate changes to the team for questions and comments. 
    (Note: Only required for issues of size `Medium` or larger)

## ✅ Post-merge checklist ##

- [ ] Feature branch deleted after merge to clean up repository.
- [ ] Verified that all checks pass on parent branch (e.g., main or release-name) after merge.

2024-12-04 20:37 UTC, tkol2022 requested changes
I did a search in the repo for references to the sharepoint 4.2 policy and I found some files that were not updated or deleted. Can you take a look and see if you need to perform any additional changes?

![image](https://github.com/user-attachments/assets/f589186b-562d-4b7b-992d-2aa2ee8d7c91)

2024-12-09 23:08 UTC, mitchelbaker-cisa requested changes
Ran ScubaGear and seeing no traces of policy 4.2 in the output files.

I pulled your branch locally, below are the results from searching the repo for "MS.SHAREPOINT.4.2":

![Screenshot (348)](https://github.com/user-attachments/assets/a1740e27-7f07-474c-9bc5-059719fcbcc3)

If occurrences in the /Sample-Reports directory will be handled by https://github.com/cisagov/ScubaGear/issues/1466, then the only other occurrence is in [/CreateReportStubs/TestResults.json](https://github.com/cisagov/ScubaGear/blob/main/PowerShell/ScubaGear/Testing/Unit/PowerShell/CreateReport/CreateReportStubs/TestResults.json). See line number below:

![Screenshot (350)](https://github.com/user-attachments/assets/4b82a2ba-ebbe-4d7c-afae-5d2b4164bfe8)

2024-12-10 19:13 UTC, tkol2022 approved these changes

2024-12-10 20:22 UTC, mitchelbaker-cisa approved these changes

2024-12-10 21:26 UTC, ahuynhMITRE commented
good to merge @nanda-katikaneni

2024-12-11 13:56 UTC, merged