Add high risk application/service principal permissions into ScubaResults.json
cisagov/ScubaGear pull request #1462
Opened 2024-12-07 01:59 UTC by mitchelbaker-cisa

#  #
  

## 🗣 Description ##

Adds a new module AADRiskyPermissionsHelper.psm1 which has the following functions: 
- Get-ApplicationsWithRiskyPermissions
- Get-ServicePrincipalsWithRiskyPermissions
- Get-FirstPartyRiskyApplications
- Get-ThirdPartyRiskyServicePrincipals
- Format-RiskyPermission
- Format-Credentials
- Merge-Credentials

These functions serve the purpose of parsing application and service principal objects for risky permissions. The result can be found in ScubaResults.json with the following keys: `first_party_risky_applications` and `third_party_risky_service_principals`. 

First-party applications refer to applications created within your tenant, while third-party service principals refer to service principals downloaded within your tenant that are owned by an external tenant.

## 💭 Motivation and context ##

Closes #1327 

## 🧪 Testing ##

Run new PowerShell unit tests in the root directory with the following command: 
```
Invoke-Pester -Output 'Detailed' -Path '.\PowerShell\ScubaGear\Testing\Unit\PowerShell\Providers\AADProvider\AADRiskyPermissionsHelper'
```

## ✅ Pre-approval checklist ##

- [ ] This PR has an informative and human-readable title.
- [ ] PR targets the correct parent branch (e.g., main or release-name) for merge.
- [ ] Changes are limited to a single goal - *eschew scope creep!*
- [ ] Changes are sized such that they do not touch excessive number of files.
- [ ] *All* future TODOs are captured in issues, which are referenced in code comments.
- [ ] These code changes follow the ScubaGear [content style guide](https://github.com/cisagov/ScubaGear/blob/main/CONTENTSTYLEGUIDE.md).
- [ ] Related issues these changes resolve are linked preferably via [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).
- [ ] All relevant type-of-change labels added.
- [ ] All relevant project fields are set.
- [ ] All relevant repo and/or project documentation updated to reflect these changes.
- [ ] Unit tests added/updated to cover PowerShell and Rego changes.
- [ ] Functional tests added/updated to cover PowerShell and Rego changes.
- [ ] All relevant functional tests passed.
- [ ] All automated checks (e.g., linting, static analysis, unit/smoke tests) passed.

## ✅ Pre-merge checklist ##

- [ ] PR passed smoke test check.
- [ ] Feature branch has been rebased against changes from parent branch, as needed

  Use `Rebase branch` button below or use [this](https://www.digitalocean.com/community/tutorials/how-to-rebase-and-update-a-pull-request) reference to rebase from the command line.
- [ ] Resolved all merge conflicts on branch
- [ ] Notified merge coordinator that PR is ready for merge via comment mention
- [ ] Demonstrate changes to the team for questions and comments. 
    (Note: Only required for issues of size `Medium` or larger)

## ✅ Post-merge checklist ##

- [ ] Feature branch deleted after merge to clean up repository.
- [ ] Verified that all checks pass on parent branch (e.g., main or release-name) after merge.

2024-12-12 18:11 UTC, tkol2022 requested changes
I noticed code at the top of the AADRiskyPermissionsHelper that is not part of an obvious code block. It is just floating there. I would prefer if we move it into a block of code. Is there somewhere where we load up global variables or something like that?

![image](https://github.com/user-attachments/assets/6f644c2b-4db0-4a10-ab0f-906e52fdd8fd)

2024-12-12 18:54 UTC, tkol2022 commented
### Bug 
Get-ApplicationsWithRiskyPermissions does not handle API permissions that belong to apps not listed in the "resources" section of RiskyPermissions.json.

![image](https://github.com/user-attachments/assets/ed315844-e234-4a8b-af24-40e1fa69df5a)

I tested in Test Tenant 3 (E5) and it failed on this line:

![image](https://github.com/user-attachments/assets/3d41e0b8-b831-4e60-b6cf-e9f788e91490)

I tracked down what was happening and the application being audited had an API permission assigned which belongs to an app that you don't have in the RiskyPermissions.json.

![image](https://github.com/user-attachments/assets/413bfac8-b21c-4c0d-a8f2-58e4f006e051)
![image](https://github.com/user-attachments/assets/d4721418-76cb-4d23-9d04-b1610b134804)
![image](https://github.com/user-attachments/assets/8362d6c1-70b6-4ff0-8636-ef51a2329403)

### Potential fix
Check if the app id that the permission belongs to is in the "resources" section of RiskyPermissions.json and if not, you can query Graph to find its display name.

2024-12-12 18:59 UTC, tkol2022 commented
### Variable name change recommendation

I recommend to rename the variable "Resource" in Get-ApplicationsWithRiskyPermissions. It is not clear which resource we are referring to. Maybe "ResourceAppDisplayName" or something like that because the variable indicates the name of the application that a specific permission belongs to. If you use the same name elsewhere to mean the same thing, then I would change that too.

![image](https://github.com/user-attachments/assets/8dd878b8-5cd4-4388-aa6e-86602be0cc22)

2024-12-12 19:14 UTC, tkol2022 commented
### Bug
In ExportAADProvider where the Get-FirstPartyRiskyApplications and Get-ThirdPartyRiskyServicePrincipals functions are called, I recommend adding parameter validation to ensure that the input parameters RiskyApps and RiskySPs are not $null.
If the preceding functions Get-ApplicationsWithRiskyPermissions or Get-ServicePrincipalsWithRiskyPermissions encounter an error then those parameters will probably be $null and then we probably don't want to call Get-FirstPartyRiskyApplications or Get-ThirdPartyRiskyServicePrincipals.
You should also make sure that the code handles situations where the RiskyApps and RiskySPs are "empty" because your Get-FirstPartyRiskyApplications and Get-ThirdPartyRiskyServicePrincipals functions do not accept empty input objects.

The reason I noticed this is because during testing, Get-ApplicationsWithRiskyPermissions failed due to error but the code proceeded to call the subsequent functions noted above which then generated more errors and error messages.

![image](https://github.com/user-attachments/assets/cf8a515b-d781-48fe-b7ff-a35466975e91)
![image](https://github.com/user-attachments/assets/1e9767f8-bfc3-4949-bb7e-c36084e5f2ee)


Your code does not accept empty input objects.
![image](https://github.com/user-attachments/assets/d88b5132-9952-4bfe-b03c-c522fdb8b76a)

2024-12-12 19:55 UTC, tkol2022 commented
### Terms
From what I have seen in multiple web sites, "first party" can refer to applications developed by Microsoft so we might need to use another term to describe apps that the organization running ScubaGear created and owns. 

![image](https://github.com/user-attachments/assets/06b65bbc-816e-4233-977c-34ec060c4846)

https://learn.microsoft.com/en-us/troubleshoot/entra/entra-id/governance/verify-first-party-apps-sign-in
![image](https://github.com/user-attachments/assets/550b8631-2694-4b23-8741-8d93849660a4)

2024-12-12 21:27 UTC, tkol2022 commented
### Permissions to add
Mitchel, I recommend adding the permissions below to RiskyPermissions.json. Please review them and if you agree, go ahead and add them. For any additional permissions we can create a future issue to analyze all the Graph permissions and see if we want to augment or make any further changes.

- Application.Read.All (can get information on which apps or service principals can be used to gain access to the tenant)
- Organization.Read.All (can read licensing information which might help an adversary determine which security services are enabled during recon)
- RoleManagement.Read.Directory (can read which users have highly privileged roles)

2024-12-12 22:22 UTC, tkol2022 commented
### Function naming
I am wondering if we should rename the functions Get-FirstPartyRiskyApplications and Get-ThirdPartyRiskyServicePrincipals to more closely align with what they actually do and distinguish them from Get-ApplicationsWithRiskyPermissions and Get-ServicePrincipalsWithRiskyPermissions? Also the term "Get" can imply that a function is retrieving data from somewhere (database, graph, M365, etc.)

Here is what each seems to do:

- Get-FirstPartyRiskyApplications - This seems to be an aggregation function.
- Get-ThirdPartyRiskyServicePrincipals - This pulls objects from the input parameter RiskySPs that are developed by third parties. It's almost like a filter operation of sorts.

2024-12-12 22:30 UTC, tkol2022 commented
### Test Results - Test Tenant 1 (G5)

- The code seems to create the JSON in ScubaResults for both applications (owned by the organization running ScubaGear) and third party developed service principals. I went through all the apps and service principals and it seems that the code pulls only the ones that have permissions flagged as high risk in the RiskyPermissions.json file, therefore it is behaving as expected.
- The code correctly reports on apps versus third party service principals in the first_party_risky_applications and third_party_risky_service_principals nodes inside ScubaResults.

The code flagged the following numbers of objects as being associated with risk in the tenant:
**Applications** (owned by the org): 10 objects
**Third party service principals:** 2 objects

#### Missing test data
We need some test data for the KeyCredentials, PasswordCredentials and FederatedCredentials fields for objects in the third_party_risky_service_principals node of ScubaResults because right now, the service principals that were flagged have empty data in those fields.

2024-12-13 13:31 UTC, tkol2022 commented
### Test Results - Test Tenant 6 (GCC high)
The code fails with what appears to be the same problem as [reported in an earlier comment](https://github.com/cisagov/ScubaGear/pull/1462#issuecomment-2539780121)

![image](https://github.com/user-attachments/assets/d9de3a2b-f029-4eaa-81ff-5fc496c75dda)

2024-12-13 17:30 UTC, tkol2022 commented
> * c

#1471 has been added for future improvements to RiskyPermissions.json

2024-12-13 18:28 UTC, tkol2022 commented
### Performance Profiling
I noticed that the addition of the new code appears to add significant time to the execution of the AAD provider so I did some performance profiling. I tried out a couple of potential solutions and will follow-up by email with sample code and specifics. The cmdlet Get-MgBetaServicePrincipalAppRoleAssignment is invoked 720 times when running against the G5 test tenant and that is the root cause of the execution time because each one of those is a REST API call to Graph.

*execution times in screenshots below are in seconds.

#### Current code performance
![image](https://github.com/user-attachments/assets/f7a39093-14c1-4d0f-b034-9a3c64b07fcd)

#### Potential solution 1
![image](https://github.com/user-attachments/assets/401f37db-2d32-450a-9f26-8d0d79af89ce)

#### Potential solution 2
![image](https://github.com/user-attachments/assets/355f36e3-ea66-4efb-9342-fa0e9bf79eda)

2025-01-06 20:21 UTC, mitchelbaker-cisa commented
> I noticed code at the top of the AADRiskyPermissionsHelper that is not part of an obvious code block. It is just floating there. I would prefer if we move it into a block of code. Is there somewhere where we load up global variables or something like that?
> 
> ![image](https://private-user-images.githubusercontent.com/107076927/395280295-6f644c2b-4db0-4a10-ab0f-906e52fdd8fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3MzQ3NTQsIm5iZiI6MTczNDczNDQ1NCwicGF0aCI6Ii8xMDcwNzY5MjcvMzk1MjgwMjk1LTZmNjQ0YzJiLTRkYjAtNGExMC1hYjBmLTkwNmU1MmZkZDhmZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyMFQyMjQwNTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZDMwNWRlM2MxMTJjOWM0MzQ1M2UxZjFmMWM0OWQyNDQ4OTAzN2IwOTZjOWU1YzhmM2Y3MDk5ZGM5ZmFiMTk2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9._O1rRBgnWBqaF1LEsNU5C3MxdGjAMbgnKrq7Xt8VA7c)
> ### Addam's input
> 
> I asked @schrolla for his opinion and he said:
> 
> ```
> Either repeat or turn it into a function of it's own and call it within the others.
> So maybe a GetPermissionsJson private function and then just call it where needed in each function to do $PermissionsJson = Get-PermissionsJson()  and retrieve the needed object.
> Might even think about putting that function in the Utility module in case other parts of the code eventually want to access that file.  But I don't think that's strictly necessary here.
> ```

Writing another function in the existing AADRiskyPermissionsHelper.psm1 module would be simple, but I moved the global variable declaration inside of ScubaConfig.psm1 in anticipation of #1136. ([987cfd5](https://github.com/cisagov/ScubaGear/pull/1462/commits/987cfd5b0077710550f5963fb18d86417831abcd)) 

To use the RiskyPermissions.json, add `using module "./path/to/ScubaConfig.psm1"` in the file its used then call the GetInstance() method:

```
$RiskyPermissionsJson = [ScubaConfig]::GetInstance().RiskyPermissions
```

2025-01-14 23:52 UTC, mitchelbaker-cisa commented
@tkol2022 I added your batch prototype into Get-ServicePrincipalsWithRiskyPermissions. Below are the speeds it clocked in at, much better improvements compared to the original function.

![Screenshot (429)_LI](https://github.com/user-attachments/assets/b6d8619e-fd84-44ee-a28d-2a7813608729)

![Screenshot (430)](https://github.com/user-attachments/assets/25c1a046-dd17-4877-8ecf-2388c02ebf3f)

![Screenshot (428)](https://github.com/user-attachments/assets/4ce6a473-7338-4884-9044-b831989ecdfc)

2025-01-24 01:00 UTC, tkol2022 commented
### Regression testing results

#### E5 tenant
The code ran and it appears to identify both risky apps and third party service principals. The batch endpoint is working fine with no errors. The code identifies credentials on the application object and the service principal object, including third party service principals, and it contains a field IsFromApplication indicating whether the credentials were found on the app or the SP which is a nice touch.

2025-01-24 02:03 UTC, mitchelbaker-cisa commented
Tested adding a password credential to an existing service principal object. The `Format-RiskyApplications` correctly merged the password credential with the service principal's associated application registration object, which is displayed under `risky_applications` in ScubaResults.json. 

![Screenshot (449)](https://github.com/user-attachments/assets/8bfe42a5-9ff3-459b-8c76-89a66860d1b8)

Tested adding a password credential to a 3rd party application, it is possible to authenticate using the credential from the command line and query tenant data. This credential displays under risky third party service principals.

![Screenshot (446)](https://github.com/user-attachments/assets/57b04224-d4a3-4dac-a7c7-4d78bd918985)

2025-01-24 18:49 UTC, tkol2022 commented
> erged the password credential with the service principal's associated application registration object, which is displayed under `risky_applications` in ScubaResults.json

### G3 tenant
The enhancement identifies risky applications and service principals, along with their credentials and permissions as expected.

2025-01-24 18:59 UTC, tkol2022 approved these changes
Outstanding job on this. Significant enhancement.

2025-01-30 16:01 UTC, dagarwal-mitre reviewed
I had one question about a commented code block's purpose, besides that the branch works great, I focused mainly on our G3 tenant but tested briefly against the others and didn't run into any issues or errors, including running the pester tests. Great work!

2025-01-30 17:44 UTC, mitchelbaker-cisa commented on PowerShell/ScubaGear/Modules/ScubaConfig/ScubaConfig.psm1
> +    #) | ConvertFrom-Json)
Good catch, this block should be removed. I was testing importing RiskyPermissions.json into another file by referencing `[ScubaConfig]::GetInstance().RiskyPermissions`, but it was simpler to create a function with the same logic to use throughout AADRiskyPermissionsHelper.psm1 instead.

![Screenshot (473)](https://github.com/user-attachments/assets/ef3ffd48-e03e-478d-a271-98b04aae554b)

2025-01-30 17:50 UTC, mitchelbaker-cisa commented on PowerShell/ScubaGear/Modules/ScubaConfig/ScubaConfig.psm1
> +    #) | ConvertFrom-Json)
[3f795e2](https://github.com/cisagov/ScubaGear/pull/1462/commits/3f795e295073f58240079dbe9d6fb5d553542ea4)

2025-02-06 16:12 UTC, dagarwal-mitre approved these changes
Looks great, good job!

2025-02-07 21:37 UTC, mitchelbaker-cisa commented
@nanda-katikaneni ready to merge

2025-02-07 21:48 UTC, merged