Add 'v' prefix to release tag name automation
cisagov/ScubaGear pull request #225
Opened 2023-03-28 13:04 UTC by schrolla

#  #

## 🗣 Description ##

The `Build and Sign Release` action produces a draft release with a Git tag format that does not match the previously used release tags and is inconsistent with convention.  This PR addresses the issue by prefixing the new git tag with the letter 'v' consistent with previous versions and general convention.

## 💭 Motivation and context ##

This change ensures that future generated releases are tagged consistent with previous releases and convention.  

Closes #223 

## 🧪 Testing ##

Run the Build and Sign release action manually on the feature branch.  Validate that the generated draft release includes a tag name that is prefixed with 'v'.

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] *All* future TODOs are captured in issues, which are referenced
      in code comments.
- [x] All relevant type-of-change labels have been added.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
- [x] All new and existing tests pass.

## ✅ Pre-merge checklist ##

- [ ] Revert dependencies to default branches.
- [ ] Finalize version.

## ✅ Post-merge checklist ##

- [ ] Create a release.

2023-04-03 19:38 UTC, gdasher requested changes

2023-04-03 19:38 UTC, gdasher commented on .github/workflows/run_release.yaml
> +        tag_name: v${{ inputs.version }}
Can you please update the definition of this parameter on line 9 to provide an example (so people know they're supposed to leave out the v)?

2023-04-03 20:21 UTC, gdasher approved these changes

2023-04-04 17:27 UTC, nanda-katikaneni approved these changes
Looks good to me.

2023-04-04 17:28 UTC, merged