212 adjudicate structural changes to all baseline markdowns
cisagov/ScubaGear pull request #330
Opened 2023-05-11 16:37 UTC by ahuynhMITRE

Pull request to merge into the emerald branch a "starting point" for the baselines to include the following structural changes:

- REMOVE All Numbering from “Introductions”, “Assumptions”, and “Baseline” sections of the markdown. 
- ADD New baseline versioning schema to each policy.
- ADD “Last Modified” section below “Rationale” Section.
- UPDATE Group Name to remove "SHALL" and "SHOULD" language.
- UPDATE all relative references (e.g., "see above policies”) with new policy IDs.

2023-05-11 18:00 UTC, crutchfield commented on baselines/sharepoint.md
> +## 1 File and Folder Links Default Sharing Settings
```suggestion
## 1. File and Folder Links Default Sharing Settings
```

2023-05-11 18:00 UTC, crutchfield commented on baselines/sharepoint.md
> +## 2 External Sharing
```suggestion
## 2. External Sharing
```

2023-05-11 18:01 UTC, crutchfield commented on baselines/sharepoint.md
> +## 3 Sensitivity Levels
```suggestion
## 3. Sensitivity Levels 
```

2023-05-11 18:01 UTC, crutchfield commented on baselines/sharepoint.md
> +## 3 Sensitivity Levels
```suggestion
## 3. Sensitivity Levels 
```

2023-05-11 18:01 UTC, crutchfield commented on baselines/sharepoint.md
> +## 4 Guest Access to a Site or OneDrive
```suggestion
## 4. Guest Access to a Site or OneDrive
```

2023-05-11 18:02 UTC, crutchfield commented on baselines/sharepoint.md
> +## 5 Custom Scripts
```suggestion
## 5. Custom Scripts
```

2023-05-11 19:19 UTC, Sloane4 requested changes

2023-05-11 19:19 UTC, Sloane4 commented on baselines/aad.md
>  ### 2.18.1 Policy
Forgot to remove 2.18.1 from policy section header

2023-05-11 19:19 UTC, Sloane4 commented on baselines/defender.md
Is there supposed to be an implementation header for this policy

2023-05-11 19:19 UTC, Sloane4 commented on baselines/exo.md
> +## 4 Domain-Based Message Authentication, Reporting, and Conformance (DMARC)
Missing . after 4, 4 -> 4.

2023-05-11 19:19 UTC, Sloane4 commented on baselines/exo.md
Is this supposed to be missing License Requirements & Implementation section?

2023-05-11 19:19 UTC, Sloane4 commented on baselines/exo.md
Is this supposed to be missing License Requirements & Implementation section?

2023-05-11 19:19 UTC, Sloane4 commented on baselines/exo.md
Is this supposed to be missing License Requirements & Implementation section?

2023-05-11 19:19 UTC, Sloane4 commented on baselines/exo.md
Is this supposed to be missing License Requirements & Implementation section?

2023-05-11 19:19 UTC, Sloane4 commented on baselines/exo.md
Is this supposed to be missing License Requirements & Implementation section?

2023-05-11 19:19 UTC, Sloane4 commented on baselines/exo.md
Is this supposed to be missing License Requirements & Implementation section?

2023-05-11 19:19 UTC, Sloane4 commented on baselines/exo.md
Is this supposed to be missing License Requirements & Implementation section?

2023-05-11 19:19 UTC, Sloane4 commented on baselines/exo.md
>    Office 365 Minimum Viable Secure Configuration Baseline*.
Is this supposed to be missing License Requirements & Implementation section?

2023-05-11 19:19 UTC, Sloane4 commented on baselines/defender.md
>  - Requires Defender for Office 365 Plan 1 or 2. These are included with
Forgot to remove 2.4.3 from License Requirements

2023-05-11 19:19 UTC, Sloane4 commented on baselines/defender.md
> +### Policies
Since Policy is a section header should it be consistent through the document as Policy or Policies?

2023-05-11 19:35 UTC, crutchfield commented on baselines/aad.md
>  - Browser sessions SHALL not be persistent.
```suggestion
Browser sessions SHALL not be persistent.
```

2023-05-11 19:38 UTC, crutchfield commented on baselines/aad.md
> +The following built-in Azure AD roles are considered highly privileged at a minimum. Additional built-in roles that are considered highly privileged in the agency’s environment can be added to this l
```suggestion
The following built-in Azure AD roles are considered highly privileged at a minimum. Additional built-in roles that are considered highly privileged in the agency's environment can be added to this list:
```

2023-05-11 19:41 UTC, crutchfield commented on baselines/defender.md
>  - User impersonation protection SHOULD be enabled for key agency
```suggestion
User impersonation protection SHOULD be enabled for key agency
```

2023-05-11 19:41 UTC, crutchfield commented on baselines/defender.md
>  - Domain impersonation protection SHOULD be enabled for domains owned by
```suggestion
Domain impersonation protection SHOULD be enabled for domains owned by
```

2023-05-11 19:42 UTC, crutchfield commented on baselines/defender.md
>  - Domain impersonation protection SHOULD be added for frequent partners.
```suggestion
Domain impersonation protection SHOULD be added for frequent partners.
```

2023-05-11 19:42 UTC, crutchfield commented on baselines/defender.md
>  - Trusted senders and domains MAY be added in the event of false
```suggestion
Trusted senders and domains MAY be added in the event of false
```

2023-05-11 19:42 UTC, crutchfield commented on baselines/defender.md
>  - Intelligence for impersonation protection SHALL be enabled.
```suggestion
Intelligence for impersonation protection SHALL be enabled.
```

2023-05-11 19:43 UTC, crutchfield commented on baselines/defender.md
>  - Message action SHALL be set to quarantine if the message is detected
```suggestion
Message action SHALL be set to quarantine if the message is detected
```

2023-05-11 19:43 UTC, crutchfield commented on baselines/defender.md
>  - Mail classified as spoofed SHALL be quarantined.
```suggestion
Mail classified as spoofed SHALL be quarantined.
```

2023-05-11 19:43 UTC, crutchfield commented on baselines/defender.md
>  - All safety tips SHALL be enabled, including:
```suggestion
All safety tips SHALL be enabled, including:
```

2023-05-11 19:44 UTC, crutchfield commented on baselines/defender.md
>  - The above configurations SHALL be set in the default policy and SHOULD
```suggestion
The above configurations SHALL be set in the default policy and SHOULD
```

2023-05-11 19:46 UTC, crutchfield commented on baselines/defender.md
>  - Safe Links in Office 365 apps SHALL be turned on.
```suggestion
Safe Links in Office 365 apps SHALL be turned on.
```

2023-05-11 19:46 UTC, crutchfield commented on baselines/defender.md
>  - Users SHALL NOT be enabled to click through to the original URL.
```suggestion
Users SHALL NOT be enabled to click through to the original URL.
```

2023-05-11 19:49 UTC, ahuynhMITRE commented on baselines/onedrive.md
> +### Policies
will make all headers "Policies" across all baselines

2023-05-11 19:49 UTC, ahuynhMITRE commented on baselines/onedrive.md
updated!

2023-05-11 19:50 UTC, ahuynhMITRE commented on baselines/onedrive.md
> +Configuring OneDrive to sync only to agency-deined domains ensures that
updated!

2023-05-11 19:51 UTC, ahuynhMITRE commented on baselines/powerplatform.md
> +### Policies
will make all headers "Policies" across all baselines

2023-05-11 19:51 UTC, ahuynhMITRE commented on baselines/powerplatform.md
> +### Policy
will make all headers "Policies" across all baselines

2023-05-11 20:00 UTC, crutchfield requested changes
A few minor corrections to markdowns.  All are in-line so you can just accept if you agree. Then I'll approve.

2023-05-11 22:05 UTC, adhilto approved these changes
I don't have anything to add, looks good to me

2023-05-12 12:08 UTC, crutchfield approved these changes

2023-05-12 14:16 UTC, tkol2022 approved these changes

2023-05-12 16:18 UTC, Dylan-MITRE approved these changes

2023-05-12 17:17 UTC, Sloane4 commented on baselines/aad.md
> +###  Policy
This should be policies

2023-05-12 18:21 UTC, Sloane4 commented on baselines/aad.md
>  ### 2.18.1 Policy
needs to be changed to policies as well

2023-05-12 18:39 UTC, ahuynhMITRE commented on baselines/exo.md
> +- _Rationale:_ TODO
sounds good, good catch david!

2023-05-12 18:40 UTC, ahuynhMITRE commented on baselines/defender.md
> +    **Next**.
probably, will update

2023-05-12 18:42 UTC, ahuynhMITRE commented on baselines/aad.md
> +###  Policy
updated!

2023-05-15 19:07 UTC, closed without merging

2023-05-15 19:10 UTC, nanda-katikaneni commented
An updated/new PR has been approved and merged into emerald - that merged pr has all the structural changes and review suggestions. Closing this pr without merge.