Address Power Platform pilot comments and substantive changes in the baseline document
cisagov/ScubaGear pull request #400
Opened 2023-06-26 16:51 UTC by buidav

## 🗣 Description ##

- Reformatted the baseline document with new structure and policy identifiers
- Added additional language and resources in the intro to address pilot feedback
- Added a new Policy Group for Power Pages
- Refine and update policy statements to address pilot feedback. 
- Updated implementation steps for any out of date instructions

TODO: address code updates in #399

## 💭 Motivation and context ##
closes #239 
closes #287
closes #311 

## 🧪 Testing ##
- Retested instructions for the Power Platform policies on commercial and GCC tenants.
- Addressed comments in the comments matrix.

## ✅ Pre-approval checklist ##

- [ ] This PR has an informative and human-readable title.
- [ ] Changes are limited to a single goal - *eschew scope creep!*
- [ ] *All* future TODOs are captured in issues, which are referenced
      in code comments.
- [ ] All relevant type-of-change labels have been added.
- [ ] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
- [ ] Tests have been added and/or modified to cover the changes in this PR.
- [ ] All new and existing tests pass.

## ✅ Pre-merge checklist ##

## ✅ Post-merge checklist ##

2023-06-29 21:55 UTC, rgbrow1949 requested changes
Found grammatical errors. I'm still reviewing.

2023-06-30 01:25 UTC, rgbrow1949 requested changes
Grammar Notes: 
- (Line 27) drop "that".
- (Line 29) add comma after "get notifications".
- (Lines 35-37) Put a comma after "a Power App" before the "or". Also, make the objects of the sentence: "proxy" and wrapper", plural. So: "These are proxies or wrappers around an API that allow the underlying service to be accessed from Power Automate Workflows, a Power App, or Azure Logic Apps. 
- (Line 42) Comma after "update".
- (Line 80) Comma after "Power Apps".
- (Line 92) "controls" should be singular: 'control'.
- (Line 98) Drop "the" before "Global Admin".
- (Line 119, 236, 325, 371) Is it supposed to read: "your tenant's respective Power Platform Admin Center"? If so, why is "Power Platform admin Center" in square brackets? 
- (Line 137) Put a comma after "To secure Power Platform environments".
- (Line 150-151) Drop the comma after "blocked".
- (Line 154) Should it be "in the Power Platform" or just "in Power Platform"?
- (Line 217) Agency is mispelled.
- (Line 256-278, 334-337, 371-384) Inconsistent spaces before instruction # compared to previous and future amount of spaces before instruction numbers. (1 space vs. 2 spaces).
- (Line 254) Category should not be capitalized. Should be "category".
- (Line 349) Comma after clickjacking.

2023-07-04 01:43 UTC, rgbrow1949 approved these changes

2023-07-06 15:40 UTC, nanda-katikaneni requested changes
A few styling and incorrect reference to be fixed.

2023-07-06 15:40 UTC, nanda-katikaneni commented on baselines/powerplatform.md
Please update the title as per new style guide. (viz. CISA M365 Security Configuration Baseline for Power Platform)

2023-07-06 15:40 UTC, nanda-katikaneni commented on baselines/powerplatform.md
> +1.  Refer to steps **8** and **9** in the **MS.POWERPLATFORM.2.3v1** instructions to meet this policy.
This step within MS.POWERPLATFORM.2.3v1 refers to itself for nonexistent steps 8&9 - a typo? seems reference should be to "2.1v1" steps 8&9.

2023-07-07 19:14 UTC, closed without merging