Update aad scubagear code to align to revised baseline
cisagov/ScubaGear pull request #408
Opened 2023-06-30 15:48 UTC by Sloane4

#  #

## 🗣 Description ##
Rearrange, add, & delete aad policy code to match updated baseline. Rearrange, add, & delete aad unit tests to match aad code. 

## 💭 Motivation and context ##

Necessary to match new aad baseline policies & format (policy ID ex "2.1" -> "MS.AAD.1.1v1")
Closing #395 

## 🧪 Testing ##

- Unit Tests
- Functional Tests

## ✅ Pre-approval checklist ##

- [ ] This PR has an informative and human-readable title.
- [ ] Changes are limited to a single goal - *eschew scope creep!*
- [ ] *All* future TODOs are captured in issues, which are referenced
      in code comments.
- [ ] All relevant type-of-change labels have been added.
- [ ] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [ ] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [ ] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
- [ ] Tests have been added and/or modified to cover the changes in this PR.
- [ ] All new and existing tests pass.

## ✅ Pre-merge checklist ##

- [ ] Revert dependencies to default branches.
- [ ] Finalize version.

## ✅ Post-merge checklist ##

- [ ] Create a release.

2023-06-30 20:11 UTC, tkol2022 commented on Rego/AADConfig.rego
We have a separate set of issues for updating the policy logic. For this specific one we have #332

2023-06-30 20:59 UTC, tkol2022 requested changes
I tested the tool on my laptop and a virtual machine against the G5/E5 tenants and I'm consistently getting the error below:

![image](https://github.com/cisagov/ScubaGear/assets/107076927/ddfdce22-e568-414f-91d6-1bdf9e7b32e6)

2023-07-02 00:29 UTC, tkol2022 commented on Rego/AADConfig.rego
Agreed. @Sloane4 please include this recommendation into this PR. Copying @ssatyapal123 for awareness since there won't be a need for a separate code change for the global admin max.

2023-07-03 12:47 UTC, Sloane4 commented
> I tested the tool on my laptop and a virtual machine against the G5/E5 tenants and I'm consistently getting the error below:
> 
> ![image](https://user-images.githubusercontent.com/107076927/250198301-ddfdce22-e568-414f-91d6-1bdf9e7b32e6.png)

This is a problem that occurred when we merged in the baseline changes because of the change in the implementation format. See #405

2023-07-03 13:03 UTC, Sloane4 commented on Testing/Unit/Rego/AAD/AADConfig_07_test.rego
> +test_PrivilegedUsers_Incorrect_V2 if {
Updated, please confirm

2023-07-03 13:08 UTC, Sloane4 commented on Rego/AADConfig.rego
> +# At this time we are unable to test for X because of Y
This was something the original coder was supposed to fill out so we know why it was not implemented with the hope that we can implement it someday if things change. I took a stab at it.... so, please confirm

2023-07-03 13:13 UTC, Sloane4 commented on Rego/AADConfig.rego
> +    GroupExclusionsFullyExempt(Cap, "MS.AAD.1.1v1") == true
updated, please confirm

2023-07-03 13:51 UTC, Sloane4 commented on Rego/AADConfig.rego
> +# because of the run time & infomation generated will be greater than its usefulness.
Updated, please confirm

2023-07-03 17:27 UTC, tkol2022 approved these changes
### Testing Summary

- Had to remove the four hash tags for the implementation sections in AAD.md so that I could run the revised AAD Rego code locally and bypass the report creation error. As Cassey mentioned we have 405 queue up to fix the error when the report is generated so that will be a priority after this PR is merged.
- The code runs and produces a report that lines up with the revised markdown document.
- I reviewed the Rego code and the policies appear to be mapped to the revised markdown accurately. I had to perform functional testing on a couple of the Rego policies that I was unsure about and they passed the test.

Nice work @Sloane4 and I noticed that you enhanced some of the Rego policy names, etc. !

2023-07-03 18:58 UTC, merged