formal internal review of Sharepoint / OneDrive baseline
cisagov/ScubaGear pull request #444
Opened 2023-07-18 01:37 UTC by tkol2022

# Scope #

This PR is designed to facilitate a formal review of the revised Sharepoint / OneDrive baseline from CISA Scuba principals and the Scuba development team. Following this review the baseline should be in a state for sending to the CISA agency formal review process.

## Note

We have active development issues against this baseline at the moment. If any changes occur during this baseline review which materially affect the ScubaGear code, it may require a notification to the affected developers.

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [ ] *All* future TODOs are captured in issues, which are referenced
      in code comments.
- [x] All relevant type-of-change labels have been added.
- [ ] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.

## ✅ Pre-merge checklist ##

- [ ] Revert dependencies to default branches.
- [ ] Finalize version.

2023-07-26 00:07 UTC, tkol2022 commented
Ping @gdasher - any comments on this baseline? thx

2023-07-27 15:38 UTC, nanda-katikaneni approved these changes
Looks good to me.

2023-08-03 16:21 UTC, gdasher requested changes

2023-08-03 17:09 UTC, tkol2022 commented on baselines/sharepointonedrive.md
- We can add this to the Rationale: "By approved security groups we are referring to a list of agency designated [Azure AD Security Groups](https://learn.microsoft.com/en-us/microsoft-365/community/all-about-groups#azure-ad-security-groups) that contain a list of users allowed to share documents externally." Do you think that will help? 
- The reason we split it up into two policies 1.3 (sharing restricted to domains) and 1.4 (sharing restricted to users in specific security groups) is because these are two separate configurations in the Sharepoint portal. The previous policy also required both configurations to be compliant even though the name of the policy group may have implied that it was a choice of one or the other. Here is the previous policy bullet: "External sharing SHOULD be limited to approved domains and security groups per interagency collaboration needs".
- Since external sharing carries a lot of risk, how about we do this? How about we can keep 1.3 as a SHALL and make 1.4 a SHOULD? This way if an agency only restricts external sharing by specifying the allowed domains and does not implement the security groups restriction, they will only receive a Warning for 1.4? I will caution that in theory an agency could do something crazy like specify gmail.com as an allowed external domain for policy 1.3 which is like saying users can share with the world, but let's go with whatever you think makes sense.

2023-08-14 17:07 UTC, ahuynhMITRE commented on baselines/sharepointonedrive.md
updating MS.SHAREPOINT.1.3v1 & MS.SHAREPOINT.1.4v1 to combine the policies for agencies to use either to pass the policy.

2023-08-14 17:31 UTC, ahuynhMITRE commented on baselines/sharepointonedrive.md
added this note to instructions.

2023-08-14 17:38 UTC, ahuynhMITRE commented on baselines/sharepointonedrive.md
updated

2023-08-14 17:38 UTC, ahuynhMITRE commented on baselines/sharepointonedrive.md
updated to use bold syntax

2023-08-14 17:42 UTC, ahuynhMITRE commented on baselines/sharepointonedrive.md
updated instructions

2023-08-17 15:58 UTC, ahuynhMITRE commented
> Resolved several of my comments that were addressed, but found a few other minor formatting issues. Would recommend going thru implementation instructions to ensure punctuation is used consistently throughout. While not shown in the style guide, punctuation is used (mostly) consistently across the latest baseline implementation instructions.

Went through the implementation sections to consistently add punctuation to each step and updated a few suggestions missed

2023-08-22 14:10 UTC, ahuynhMITRE commented
@nanda-katikaneni good to merge!

2023-08-29 17:25 UTC, gdasher commented
Ready to go.

2023-08-29 17:25 UTC, gdasher approved these changes

2023-08-29 17:26 UTC, ahuynhMITRE commented
good to merge @nanda-katikaneni

2023-08-29 17:52 UTC, merged