Update MS.DEFENDER.4.1 and MS.DEFENDER.4.2 assessment checks
cisagov/ScubaGear pull request #574
Opened 2023-10-06 13:21 UTC by schrolla

#  #

## 🗣 Description ##

Updates in this pull request align the old Defender Data Loss Prevention (DLP) assessment code with the new baseline version policies and ensures the new assessment only produces a single test result for each policy statement rather than multiple results per statement.  These updates include:

- Merged results for MS.DEFENDER.4.1v1 to ensure minimum sensitive info types are included in the DLP custom policy
- Merged results for MS.DEFENDER4.2v1 that checks that custom policy includes desired locations
- Adding support to MS.DEFENDER4.2v1 to check that the Device location is included as per policy update
- Adding initial support for detection of sensitive info types in advanced DLP rules in policies
  Note: Full support for advanced rules is beyond scope of this PR and captures as TODO in #575 

## 💭 Motivation and context ##

Changes were necessary to support updated architecture that expects a single test result for each unique baseline policy ID rather than multiple results.  Updates were also required to support baseline policy updates that expanded recommended DLP locations and due to a M365 Defender change that defaults to advanced rule syntax for new custom policies that changed the internal representation of sensitive info types included in the rules causing false negatives without an update.

Closes #491 
Closes #492 
Closes #404

## 🧪 Testing ##

Validated that all unit tests pass for Defender 4 policies.  Ran `Invoke-Scuba -p defender` against G5/GCC high tenants and ensured results matched those expected for DLP policies.

## ✅ Pre-approval checklist ##

- [X] This PR has an informative and human-readable title.
- [X] Changes are limited to a single goal - *eschew scope creep!*
- [X] *All* future TODOs are captured in issues, which are referenced
      in code comments.
- [X] All relevant type-of-change labels have been added.
- [X] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
- [X] Tests have been added and/or modified to cover the changes in this PR.
- [X] All new and existing tests pass.

## ✅ Pre-merge checklist ##

- [x] Rebase current branch with parent branch to sync changes

## ✅ Post-merge checklist ##

- [ ] Verify that no additional tests failed after the merge on parent branch

2023-10-11 20:50 UTC, tkol2022 commented
### Testing 4.1 initial results - bug found
Rego policy check for Defender 4.1 produces a Pass when the DLP policy Status is set to Test in the Admin portal (this is represented as TestWith Notifications in the API). The only status that should produce a Pass is the On status (i.e. when the policy is enabled).

After examining the Rego 4.1 function named SensitiveRules, I think it is looking at the wrong JSON field in dlp_compliance_policies. Right now it is looking for Policy.Enabled == true, but I think it should be examining the Policy field named Mode for a value of "Enable". Please verify if this is correct.

Here are some screenshots of the three possible states for the Mode field based on my testing.
![image](https://github.com/cisagov/ScubaGear/assets/107076927/c885343a-b712-44d3-8242-0dcfb229ea72)
![image](https://github.com/cisagov/ScubaGear/assets/107076927/eb36b606-e30d-4deb-a32c-8f84d27416da)
![image](https://github.com/cisagov/ScubaGear/assets/107076927/3d1bcb70-e1bb-4566-a586-252efa4c0b6e)

2023-10-12 14:28 UTC, Sloane4 commented on Rego/DefenderConfig.rego
> +	Rules.Disabled == false
_Drive by review (blame ted)_ indentation is off in line 459 & 460, I believe tab was used without soft tab being enabled leading these 2 lines to being indented base on what spacing tab is set to for the user.

2023-10-12 14:29 UTC, Sloane4 commented on Rego/DefenderConfig.rego
> +	Conditions := [ contains(RuleText, "U.S. Social Security Number (SSN)"),
_Drive by review (blame ted)_ indentation is off in line 476, I believe tab was used without soft tab being enabled leading these 2 lines to being indented base on what spacing tab is set to for the user/

2023-10-12 20:24 UTC, tkol2022 commented
### Baseline document issue
@ahuynhMITRE for awareness.

Defender baseline document refers to tax ids as U.S. Individual Taxpayer Identification Numbers (**TIN**) but in the Microsoft portal (including the Rego code) they are referred to as U.S. Individual Taxpayer Identification Number (**ITIN**) with the "I" before the TIN. This was confusing when I was trying to follow the instructions because I wasn't sure I was selecting the correct type.

![image](https://github.com/cisagov/ScubaGear/assets/107076927/f7f367a5-ec77-4768-b042-dc841522b30f)
![image](https://github.com/cisagov/ScubaGear/assets/107076927/d560b4a7-981f-4c61-8ac0-d7d1bde69e07)

2023-10-12 21:39 UTC, tkol2022 commented
### No DLP Devices option for the 4.1 policy for the locations to apply it to in some tenants
The MITRE E5 tenant does not a Devices option when implementing the instructions for policy 4.1 and ends up producing a Warning in the report because it fails the check. I also recommend taking a look at what's available in the G3/E3 test tenants.

![image](https://github.com/cisagov/ScubaGear/assets/107076927/ce4f5143-5894-492e-b7aa-2b04b213ca08)
![image](https://github.com/cisagov/ScubaGear/assets/107076927/3f7b3e0f-5246-4562-948d-5a371fb6931e)
![image](https://github.com/cisagov/ScubaGear/assets/107076927/dc0df849-f5c1-4086-88ed-3897d281beda)

2023-10-12 21:59 UTC, tkol2022 commented
### Baseline enhancement suggestion
Please review and if you think it is worth it, open a separate future enhancement issue.

When defining DLP rules, there is an option to allow users to **override** the rule in Sharepoint, OneDrive, Teams, Exchange. This seems risky and counter to the purpose of defining a DLP rule that is meant in our case to **Block** users from performing the action. Maybe we should include instructions to ensure that this option is not selected and add a check to ScubaGear. Not sure if it is worth the trouble, but something to consider.

![image](https://github.com/cisagov/ScubaGear/assets/107076927/0a6580b3-8802-4f78-9bbb-9a5be49b47e0)

2023-10-12 22:19 UTC, tkol2022 commented
### This does not seem quite right for 4.2
This test was in the MITRE E5 tenant.
I created a compliant DLP policy and ran ScubaGear. The report shows a Warning (failed the test) for 4.2 and a message of "No enabled policy found that applies to: Devices". So far so good.

![image](https://github.com/cisagov/ScubaGear/assets/107076927/c8d3f420-f40d-49ae-b7fc-8df0527806b1)

Then I turned Off the DLP rules inside the policy and ran ScubaGear again.

![image](https://github.com/cisagov/ScubaGear/assets/107076927/21dbc478-c955-4af4-ba79-9fa8b7c74a4e)

I noticed that the ScubaGear report shows a different message for 4.2 now, "**No enabled policy found that applies to: Devices, Exchange, OneDrive, SharePoint, Teams**". Notice that the message now indicates that the policy is not applicable to Exchange, OneDrive, Sharepoint and Teams, but I did not change that part of the configuration. See below.

![image](https://github.com/cisagov/ScubaGear/assets/107076927/5cf23ad5-6cc1-4468-a488-d54c895338f2)

I was expecting the message to stay the same as "No enabled policy found that applies to: Devices" since I didn't make any changes to the **Choose locations to apply the policy** part of the policy.

2023-10-12 22:39 UTC, tkol2022 commented
### 4.3 bug
Although this PR is scoped to 4.1 and 4.2, the implementation instructions for policy 4.1 span across 4.1, 4.2, 4.3 and 4.4 since they are all within the same DLP configuration in the compliance portal. Decide if you want to handle this within this PR or simply create a separate issue for it.

I created a DLP policy that is compliant with all the requirements in the 4.1 instructions, except that instead of selecting the option to **Block everyone**, I selected **Block only people outside your organization**. I expected ScubaGear to produce a Fail in the report for 4.3 but it produced a Pass.

![image](https://github.com/cisagov/ScubaGear/assets/107076927/da50f97f-ab0a-4be5-beed-7723e6887f7a)
![image](https://github.com/cisagov/ScubaGear/assets/107076927/0e979c71-7560-454b-9c13-2e2e0c5415fe)

![image](https://github.com/cisagov/ScubaGear/assets/107076927/c9817f3c-6881-4d17-a7f6-758a3b9624da)

![image](https://github.com/cisagov/ScubaGear/assets/107076927/2975e4b9-e1a3-4981-8562-22397a77afc2)

2023-10-13 13:22 UTC, tkol2022 commented
> This is outside the scope of this PR, a known issue, and has a separate issue that is currently being worked.
> 
> > ### 4.3 bug
> > Although this PR is scoped to 4.1 and 4.2, the implementation instructions for policy 4.1 span across 4.1, 4.2, 4.3 and 4.4 since they are all within the same DLP configuration in the compliance portal. Decide if you want to handle this within this PR or simply create a separate issue for it.
> > I created a DLP policy that is compliant with all the requirements in the 4.1 instructions, except that instead of selecting the option to **Block everyone**, I selected **Block only people outside your organization**. I expected ScubaGear to produce a Fail in the report for 4.3 but it produced a Pass.
> > ![image](https://user-images.githubusercontent.com/107076927/274748111-da50f97f-ab0a-4be5-beed-7723e6887f7a.png) ![image](https://user-images.githubusercontent.com/107076927/274748142-0e979c71-7560-454b-9c13-2e2e0c5415fe.png)
> > ![image](https://user-images.githubusercontent.com/107076927/274747853-c9817f3c-6881-4d17-a7f6-758a3b9624da.png)
> > ![image](https://user-images.githubusercontent.com/107076927/274747925-2975e4b9-e1a3-4981-8562-22397a77afc2.png)

can you link to the issue here so we can have it for record keeping?

2023-10-13 13:24 UTC, tkol2022 commented
> nly focused on policies with those locations you'd get false positives for policies that apply to all those locations, but don't have the proper sensitive info type rule

i cannot think of any so let's keep it as is. thanks for checking it out!

2023-10-13 16:01 UTC, tkol2022 commented
### Potential bug in policy 4.1 - ScubaGear produces Pass in some scenarios where all the required sensitive info types are not covered
For the scenario described below in the MITRE E5 tenant, I expected ScubaGear to produce a Fail for 4.1 because for Teams I did NOT have all the required sensitive info types covered. Below is a play by play.

Create policy - "ted policy 2" - See configuration below. Covers Exchange, Sharepoint, OneDrive.
![image](https://github.com/cisagov/ScubaGear/assets/107076927/e7bd3ffa-79ea-441b-96fc-70adcc4a31b9)
![image](https://github.com/cisagov/ScubaGear/assets/107076927/03ed09f2-695e-46d8-a96e-abe647840cca)

Create policy - "ted policy 1" - Configuration below. Covers Teams.
![image](https://github.com/cisagov/ScubaGear/assets/107076927/a1c6ceb0-d5d7-4ef8-bead-9810d7a36c1e)
![image](https://github.com/cisagov/ScubaGear/assets/107076927/f00fab72-fcac-4c47-bc7a-bb410634accb)

Notice that for the Teams rule above, that only ITIN is included. The rule is missing SSN and Credit Card number which are required per the baseline.

2023-10-13 22:35 UTC, tkol2022 commented
I have completed my review of this PR. The only pending potential bug is in the comment labelled "ScubaGear produces Pass in some scenarios where all the required sensitive info types are not covered". Thanks! Let me know if this needs regression testing if any fixes come up.

2023-10-16 15:00 UTC, tkol2022 commented
### 

> ### No DLP Devices option for policy 4.2 w/r/t locations to apply it to in some tenants
> The MITRE E5 tenant does not offer a Devices option when implementing the instructions for policy 4.1 and ends up producing a Warning in the report because it fails the check. I also recommend taking a look at what's available in the G3/E3 test tenants.
> 
> ![image](https://user-images.githubusercontent.com/107076927/274737840-ce4f5143-5894-492e-b7aa-2b04b213ca08.png) ![image](https://user-images.githubusercontent.com/107076927/274738027-3f7b3e0f-5246-4562-948d-5a371fb6931e.png) ![image](https://user-images.githubusercontent.com/107076927/274738569-dc0df849-f5c1-4086-88ed-3897d281beda.png)

After discussing the finding that the DLP "devices" (aka DLP for Endpoint) option is not available in all tenants with @schrolla I recommend that we make a decision on how best to handle this. Pinging @ahuynhMITRE @buidav for awareness.

- Should ScubaGear check to see if the tenant is licensed for DLP for Endpoint before performing the Rego check for "devices"? This would be similar to how we check for a specific license in other Defender policies. I was unable to locate a specific license or other configuration in the JSON that would indicate that a tenant has the DLP "devices" option.
- Another option @schrolla offered is that we could display a message in the report that would caveat findings if the tenant fails the specific DLP check for devices.
- I think we could also remove the Rego check for devices from Emerald and decide on how to handle this during the next release, perhaps after further research and testing.

Below are my notes from further investigation that I performed which could inform the discussion.

- Baseline section 4 license requirements state that "DLP for Endpoint requires an E5 or G5 license" but in the G3 test tenant I am able to select the Devices option when creating a DLP policy in the portal. In G3, I was able to create a device policy by using the portal and by the Cmdlet below. Does the fact that I am able to create a Devices DLP policy in the G3 portal conflict with the baseline license requirements section?

`New-DlpCompliancePolicy -Name "TedsDevicePolicy" -Comment "Teds device policy" -EndpointDlpLocation "All" -Mode Enable
`

- I found out that the reason DLP for endpoint is not available in the MITRE E5 tenant because it is a **developer tenant** (look at screenshot below) (this is my theory anyway). I tested the New-DlpCompliancePolicy cmdlet above in our E5 tenant and it produces the error message "A parameter cannot be found that matches parameter name 'EndpointDlpLocation'". [Checkout this link about the differences between M365 E5 & M365 E5 Developer](https://answers.microsoft.com/en-us/msoffice/forum/all/differences-between-m365-e5-m365-e5-developer/5df3421c-e2d4-48ee-abc2-bd3c6d149381).

![image](https://github.com/cisagov/ScubaGear/assets/107076927/77b6548d-c003-4575-a434-e5b1bbda3246)
![image](https://github.com/cisagov/ScubaGear/assets/107076927/090d044d-f90d-4193-896d-62dc713d9d2e)

2023-10-16 16:25 UTC, Sloane4 requested changes

2023-10-16 16:25 UTC, Sloane4 commented on Rego/DefenderConfig.rego
> +    "RequirementMet" : Status,
Remove comma

2023-10-16 16:25 UTC, Sloane4 commented on Testing/Unit/Rego/Defender/DefenderConfig_04_test.rego
> +test_ContentContainsSensitiveInformation_Incorrect_V1 if {
This is a duplicate title, V1 already exists

2023-10-16 16:25 UTC, Sloane4 commented on Rego/DefenderConfig.rego
> +    count([Condition | Condition = Conditions[_]; Condition == true]) > 0
Update unification operator to assignment operator `count([Condition | Condition := Conditions[_]; Condition == true]) > 0`

```suggestion
    count([Condition | Condition := Conditions[_]; Condition == true]) > 0
```

2023-10-16 17:42 UTC, tkol2022 commented
> ### Potential bug in policy 4.1 - ScubaGear produces Pass in some scenarios where all the required sensitive info types are not covered
> For the scenario described below in the MITRE E5 tenant, I expected ScubaGear to produce a Fail for 4.1 because for Teams I did NOT have all the required sensitive info types covered. Below is a play by play.
> 
> Create policy - "ted policy 2" - See configuration below. Covers Exchange, Sharepoint, OneDrive. ![image](https://user-images.githubusercontent.com/107076927/274952138-e7bd3ffa-79ea-441b-96fc-70adcc4a31b9.png) ![image](https://user-images.githubusercontent.com/107076927/274952214-03ed09f2-695e-46d8-a96e-abe647840cca.png)
> 
> Create policy - "ted policy 1" - Configuration below. Covers Teams. ![image](https://user-images.githubusercontent.com/107076927/274952401-a1c6ceb0-d5d7-4ef8-bead-9810d7a36c1e.png) ![image](https://user-images.githubusercontent.com/107076927/274952451-f00fab72-fcac-4c47-bc7a-bb410634accb.png)
> 
> Notice that for the Teams rule above, that only ITIN is included. The rule is missing SSN and Credit Card number which are required per the baseline.

Discussed this with @schrolla via chat. Based on his interpretation of the policy, he advised that a single custom policy must contain all the necessary sensitive info types as opposed to having multiple policies combining to meet the requirement.

Sounds good to me. I also think we could implement logic to check across multiple policies in the future if there is strong feedback from users that it is necessary. I consider this resolved. Thanks @schrolla !

2023-10-16 17:44 UTC, tkol2022 approved these changes
Thanks for taking and answering all my feedback. The topic of determining how to address the fact that we probably want to adjust our Rego code to check if the tenant has the licenses or features necessary to implement DLP for Teams and/or Devices will be addressed in a separate GitHub issue in a future release.

2023-10-16 19:34 UTC, Sloane4 commented on Rego/DefenderConfig.rego
> +    Rules.AdvancedRule
because you are not able to replicate the case, do you know if this even works as intended. I do not see this case tested in the unit tests.

2023-10-16 19:50 UTC, Sloane4 approved these changes

2023-10-16 22:41 UTC, nanda-katikaneni commented
Based on separating pending items into separate issues and a quick test to verify the branch on G5...merging it into emerald.

2023-10-16 22:42 UTC, merged