Add PowerShell linter
cisagov/ScubaGear pull request #705
Opened 2023-12-06 19:10 UTC by james-garriss

#  #

Add a new workflow with MegaLinter set to run PowerShell and YAML. 

I also added a new directory, MegaLinter, that contains the config files and a READE to explain how to use them.

## 💭 Motivation and context ##

This provides linting to improve the quality of the code.

## 🧪 Testing ##

Ran MegaLinter both manually on a VM and through the new workflow.  It reports errors.

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [ ] *All* future TODOs are captured in issues, which are referenced
      in code comments.

MegaLinter can lint other files in our repo, but these are not captured in issues, as it is unclear if we want to take advantage of them.  MegaLinter does not have a linter for Rega/OPA.

- [x] All relevant type-of-change labels have been added.

## ✅ Pre-merge checklist ##

- [ ] Revert dependencies to default branches.
- [ ] Finalize version.

## ✅ Post-merge checklist ##

- [ ] Create a release.

2023-12-07 12:47 UTC, james-garriss commented
The Lint Check fails because there's a lot of PS code and YAML files in the repo that do not conform to the linting standards used by these linters.  This is expected and should not block this PR.  At this point, this workflow is merely informative.

2023-12-07 14:23 UTC, crutchfield requested changes
This looks like a usefully tool that will contribute to better code as we move forward.  I would like to see it's triggers refined.  We also need to reconsile error reporting - if it reports errors then they need to be errors we intend to fix; otherwise, don't report.

2023-12-07 14:23 UTC, crutchfield commented on MegaLinter/README.md
> +yamllint is a linter for YAML that is configured by a `.yamllint.yml` file that must be int he root directory.  It uses the disable value to disable undesired checks (e.g., `document-start: disable`)
```suggestion
yamllint is a linter for YAML that is configured by a `.yamllint.yml` file that must be in the root directory.  It uses the disable value to disable undesired checks (e.g., `document-start: disable`).  Much like the MegaLinter config file, the yamllint config file is copies from the `/MegaLinter` subdirectory to the root directory by the GitHub Action workflow.
```

2023-12-07 14:23 UTC, crutchfield commented on .github/workflows/run_linter.yaml
I am struggling with the concept that 'informational' and 'warning' equates to error.  For file, PowerShell/ScubaGear/Modules/Providers/ExportDefenderProvider.psm1 , the PowerShell linter identified 1 informational severity item but reports the file level as an error.  Can this be configured?

2023-12-07 14:23 UTC, crutchfield commented on .github/workflows/run_linter.yaml
Yaml linter reporting is off a bit as well.  Reports 1 error and suggests see details.  I don't see details (unless it is meaning look at individual file details.  But this is not one error -- they have multiple errors.  

![image](https://github.com/cisagov/ScubaGear/assets/7025068/27a19c10-fb75-4da7-9cbb-da3057a58f88)

2023-12-07 14:23 UTC, crutchfield commented on .github/workflows/run_linter.yaml
I recommend we either 1) generate a high priority set of issues to address errors or 2) change workflow(s) to warn or pass until it is ready for production.

2023-12-07 15:26 UTC, james-garriss commented
> if it reports errors then they need to be errors we intend to fix; otherwise, don't report

I hear you.  Addam's thought was that we should use this tool for a while in an informative manner for a while to see if we are happy with its linting recommendations.  If we are, then can move it to one or more of the other workflows.  If we are not, then we can drop or use other linters within it.  That seemed like a good idea to me.

2023-12-07 15:28 UTC, james-garriss commented on .github/workflows/run_linter.yaml
> +on:
Added workflow dispatch.

2023-12-07 15:30 UTC, james-garriss commented on .github/workflows/run_linter.yaml
Are you saying you want the Powershell workflow to only run when Powershell is checked in, etc?  So there would be one workflow for each time of code/format that we check?

2023-12-07 15:33 UTC, james-garriss commented on MegaLinter/README.md
> +yamllint is a linter for YAML that is configured by a `.yamllint.yml` file that must be int he root directory.  It uses the disable value to disable undesired checks (e.g., `document-start: disable`)
Typo fixed.

2023-12-07 15:35 UTC, crutchfield commented
> > if it reports errors then they need to be errors we intend to fix; otherwise, don't report
> 
> I hear you. Addam's thought was that we should use this tool for a while in an informative manner for a while to see if we are happy with its linting recommendations. If we are, then can move it to one or more of the other workflows (where it could be used to force errors to be fixed). If we are not, then we can drop or use other linters within it. That seemed like a good idea to me.

I do not disagree with @schrolla on using the tool -- I quick look at the reported items look like good suggestions.  What I am opposed to is putting a workflow in place we know is configured to fail without any near term plans to fix.  I recommend it be configure to either 1) always pass or 2) allow failure because we have documented issue that will address them in the (hopefully - near) future.

2023-12-07 15:44 UTC, crutchfield commented on .github/workflows/run_linter.yaml
> Are you saying you want the Powershell workflow to only run when Powershell is checked in, etc? So there would be one workflow for each time of code/format that we check?

Yes.  If I change just a YAML file I don't need to see output from a PowerShell linter.  I'd expect something like this"
`  push:
    paths:
      - "**.yaml"
      - "**.yml"`
      - 
Similar to the run_psscriptanalyzer workflow.

2023-12-07 15:45 UTC, crutchfield commented on .github/workflows/run_linter.yaml
> > consider seperate jobs for the different linters so they can be run in parallel.
> 
> It's reporting that it takes 3 seconds to lint the YAML. There wouldn't be any time savings, but I can still do it. My concern is that it might take a bit longer overall, as the pull step will build the container twice. Let me test...

This is not my recommended path - only an option if seperate workflows are not an option.

2023-12-07 15:45 UTC, james-garriss commented on .github/workflows/run_linter.yaml
Ok, it knocked 5 seconds off the total time.  Progress!

2023-12-07 15:53 UTC, james-garriss commented on .github/workflows/run_linter.yaml
I found a report where someone else found the same issue for a different linter in ML.  I wonder if the best thing we can do is file another report.

2023-12-07 16:00 UTC, crutchfield commented on .github/workflows/run_linter.yaml
Not a bad idea since they say that was fixed Aug 23, 2021 by [PR](https://github.com/oxsecurity/megalinter/pull/682) on same day as posted (maybe?)..

2023-12-07 16:17 UTC, james-garriss commented on .github/workflows/run_linter.yaml
The error reporting seems to be working fine, but the summary numbers seem to be off.  I don't know what else to do except file a bug report.  While annoying this doesn't really stop us from using the tool.

2023-12-07 17:19 UTC, james-garriss commented
I guess I would expect people to fix their code as they check it in.  The problem should resolve itself in a couple weeks.  Unless maybe we have older, stable code that no one is actively developing any more?  Yeah, in that case, we should write an issue for these sections.  Maybe a good way forward to is to merge the code, let people start making changes, and then in a couple of weeks, see what code is still failing, then I will write one or more issues to fix.

2023-12-07 21:00 UTC, james-garriss commented on .github/workflows/run_linter.yaml
Couldn't reproduce PS bug locally, as it always threw errors, so I reported the PS bug based upon our GitHub:  https://github.com/oxsecurity/megalinter/issues/3196

2023-12-08 20:37 UTC, james-garriss commented on .github/workflows/run_linter.yaml
Per our discussion today, we chose to have James fix simple YAML lints now and let others be fixed by their owners over time.  Those that are not fixed w/in 2 weeks, James will create issues for.

2023-12-08 20:39 UTC, james-garriss commented
@nanda-katikaneni , this PR is ready for merging.  It is true that there are lint failures (see above), but this is expected and per my discussion w @schrolla and @crutchfield acceptable for now.  None of these linting issues are truly errors; they are just formatting changes.  To go easy on future merge requests, we plan to let the owners of these files fix their own linting issues, and then if there are unfixed issues after a couple weeks, I (James) will create issues for the rest.  If you have concerns, feel free to set a cal event with Addam, Crutch, and I.  Thanks!

2023-12-14 16:04 UTC, james-garriss commented on MegaLinter/.mega-linter-powershell.yml
Done.

2023-12-14 16:05 UTC, james-garriss commented
I believe that I have made all requested changes, @crutchfield and @schrolla .  If there's anything else I need to do, please let me know.

2023-12-14 17:40 UTC, closed without merging