Quick Fix of Invoke-RunCached
cisagov/ScubaGear pull request #789
Opened 2024-01-11 15:12 UTC by Dylan-MITRE

#  #

## 🗣 Description ##

Invoke-RunCached broken due to change of location of Rego folder

## 💭 Motivation and context ##

Closes #784 

## 🧪 Testing ##

Import-Module .\PowerShell\ScubaGear
Invoke-RunCached -p teams 

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] *All* future TODOs are captured in issues, which are referenced
      in code comments.
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
- [x] Tests have been added and/or modified to cover the changes in this PR.
- [x] All new and existing tests pass.

## ✅ Pre-merge checklist ##

- [] Revert dependencies to default branches.
- [] Finalize version.

2024-01-11 16:22 UTC, Dylan-MITRE commented
Changed OPA path and rego folder location

2024-01-11 17:58 UTC, adhilto approved these changes
Looks great. Glad you fixed the opa path too even though I didn't explicitly call that out.

2024-01-11 20:20 UTC, mitchelbaker-cisa requested changes
Is $env:USERPROFILE\\.scubagear\Tools\ where you have opa_windows_amd64.exe stored locally? I think the default location for OPAPath should be the root directory.

```
Invoke-RunRego : Error with the Teams Rego invocation. See the exception message for more details:  Error calling the OPA executable: The term 'C:\Users\mitchelbaker\.scubagear\Tools\opa_windows_amd64.exe' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the      
spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Users\mitchelbaker\Documents\Github\ScubaGear\PowerShell\ScubaGear\Modules\Orchestrator.psm1:1370 char:13
+             Invoke-RunRego @RegoParams
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Invoke-RunRego
```

Other than this, the issue with the Rego folder location is resolved.

2024-01-11 20:53 UTC, mitchelbaker-cisa commented
> > Is $env:USERPROFILE.scubagear\Tools\ where you have opa_windows_amd64.exe stored locally? I think the default location for OPAPath should be the root directory.
> > ```
> > Invoke-RunRego : Error with the Teams Rego invocation. See the exception message for more details:  Error calling the OPA executable: The term 'C:\Users\mitchelbaker\.scubagear\Tools\opa_windows_amd64.exe' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the      
> > spelling of the name, or if a path was included, verify that the path is correct and try again.
> > At C:\Users\mitchelbaker\Documents\Github\ScubaGear\PowerShell\ScubaGear\Modules\Orchestrator.psm1:1370 char:13
> > +             Invoke-RunRego @RegoParams
> > +             ~~~~~~~~~~~~~~~~~~~~~~~~~~
> >     + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
> >     + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Invoke-RunRego
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Other than this, the issue with the Rego folder location is resolved.
> 
> Actually this was changed recently.
> 
> > Is $env:USERPROFILE.scubagear\Tools\ where you have opa_windows_amd64.exe stored locally? I think the default location for OPAPath should be the root directory.
> > ```
> > Invoke-RunRego : Error with the Teams Rego invocation. See the exception message for more details:  Error calling the OPA executable: The term 'C:\Users\mitchelbaker\.scubagear\Tools\opa_windows_amd64.exe' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the      
> > spelling of the name, or if a path was included, verify that the path is correct and try again.
> > At C:\Users\mitchelbaker\Documents\Github\ScubaGear\PowerShell\ScubaGear\Modules\Orchestrator.psm1:1370 char:13
> > +             Invoke-RunRego @RegoParams
> > +             ~~~~~~~~~~~~~~~~~~~~~~~~~~
> >     + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
> >     + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Invoke-RunRego
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Other than this, the issue with the Rego folder location is resolved.
> 
> Actually, no, this was also changed quite recently. See #704. If you run Setup.ps1 on the latest flipper, you'll note that you now have a .scubagear/Tools/ folder in your home directory, which is where the OPA executable will be now. @crutchfield might be able to provide more context.

Thanks for clarifying, after running .\SetUp.ps1 the tool runs as expected. Looks good!

2024-01-11 20:54 UTC, mitchelbaker-cisa approved these changes

2024-01-12 01:11 UTC, adhilto commented
@nanda-katikaneni Looks like this one is ready to be merged.

2024-01-12 15:45 UTC, merged