Add configuration file documentation to README
cisagov/ScubaGear pull request #812
Opened 2024-01-18 21:14 UTC by schrolla

#  #

## 🗣 Description ##

README.md file update to provide some sample config files to document typical use cases with
the -ConfigFilePath option

## 💭 Motivation and context ##

Provide information to user to show typical usage of config files and examples
of how they may be combined with overrides from the command line.   This
allows the user to organize and utilize config files in an efficient way for their
particular use without a lot of duplicaiton.

Closes #344 

## 🧪 Testing ##

Linter checks done on sample yaml config files

## 📷 Screenshots (if appropriate) ##

## ✅ Pre-approval checklist ##

- [X] This PR has an informative and human-readable title.
- [X] Changes are limited to a single goal - *eschew scope creep!*
- [x] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
- [X] All new and existing tests pass.

## ✅ Pre-merge checklist ##

- [ ] Rebase feature branch against parent branch if needed

## ✅ Post-merge checklist ##

- [ ] Check that all tests pass after feature branch merged into parent branch

2024-01-19 15:48 UTC, Sloane4 requested changes
Runs with out error, however double spacing after a period is not used in our other documents & looks jarring in the markdown. Request removal.

2024-01-19 15:48 UTC, Sloane4 commented on README.md
> +  If -ConfigFilePath is specified, default values will be provided for parameters that are not explicitly put in the config file.   These default values are provided explicitly in the config file tem
```suggestion
  If a -ConfigFilePath is specified, default values will be provided for parameters that are not explicitly put in the config file. These default values are provided explicitly in the config file template to guide the user, but they can be omitted from the file. Command line values options can now be provided with the -ConfigFilePath. This should reduce the number of config files needed. Examples might be: switching the M365 environment variable from commercial to gcc, switching the tenant used, or supplying credentials so they do not need to be in the config file (to facilitate sharing). The config file path defaults to the same directory where the script is executed. The file path must point to a valid configuration file with a relative or absolute path. The file can be used to specify both standard tool parameters as well as custom parameters used by the Azure Active Directory (AAD) product assessment. See [See Scuba-Config Parameter Configuration File Syntax and Examples](#invoke-scuba-parameter-configuration-file-syntax-and-examples) and [AAD Conditional Access Policy Exemptions](#aad-conditional-access-policy-exemptions) for more details.
```

2024-01-19 15:48 UTC, Sloane4 commented on README.md
> +a configuration file with the path specified by `-ConfigFilePath` parameter. It should be noted that the following parameters are support only on the command line
```suggestion
a configuration file with the path specified by `-ConfigFilePath` parameter. It should be noted that the following parameters are supported only on the command line.
```

2024-01-19 15:48 UTC, Sloane4 commented on README.md
> +shows the sample config file name and a command line example with it
```suggestion
shows the sample config file name and a command line example with it.
```

2024-01-19 15:48 UTC, Sloane4 commented on README.md
> +All of the configuration file examples referenced below are in the sample-config-files directory and the examples assume a Invoke-SCuBA is run in that directory.  Each example
```suggestion
All of the configuration file examples referenced below are in the sample-config-files directory and the examples assume a Invoke-SCuBA is run in that directory. Each example
```

2024-01-19 15:48 UTC, Sloane4 commented on README.md
> +All authentication parameters shown are samples only.  THe user must supply correct parameters
```suggestion
All authentication parameters shown are samples only. The user must supply correct parameters.
```

2024-01-19 15:48 UTC, Sloane4 commented on README.md
> +Minimal use is typically specifying a product name  and an M365 environment variable.  In this example product is entered a a single value
```suggestion
Minimal use is typically specifying a product name and an M365 environment variable. In this example product is entered a a single value.
```

2024-01-19 15:48 UTC, Sloane4 commented on README.md
> +Multiple products (can be specified in a list) and an M365 environment variable.  Note that unneeded values are commented out.
```suggestion
Multiple products (can be specified in a list) and an M365 environment variable. Note that unneeded values are commented out.
```

2024-01-19 15:48 UTC, Sloane4 commented on README.md
> +Credentials can be supplied in the config file.  However the file is not encrypted so
```suggestion
Credentials can be supplied in the config file. However the file is not encrypted so
```

2024-01-19 15:48 UTC, Sloane4 commented on README.md
> +file.  Any one of these parameters may be commented out.  If not specified ( or commented out ).  ScubaConfig will supply the default value for it unless overridden on the command line.  This default
```suggestion
file. Any one of these parameters may be commented out. If not specified ( or commented out ). ScubaConfig will supply the default value for it unless overridden on the command line. This default value does not apply to authentication parameters.
```

2024-01-22 14:53 UTC, Sloane4 approved these changes

2024-01-26 18:34 UTC, kennethpalmer commented on README.md
> +All authentication parameters must be supplied on the command line if a non-interactive login is desired.
No should stand corrected on this.  My wording was not clear.  The distinction is that there is no default for authentication parmeters.  If not in the config file,  any missing ones must be supplied in the command line.  If it is in the config file, the command line one will override.  Let me think through this wording

2024-01-26 18:51 UTC, kennethpalmer commented on README.md
> +All authentication parameters must be supplied on the command line if a non-interactive login is desired.
I'll put the suggested change in a separate commit from the batch ( prefer not to do changes in the gui unless trivial )

2024-01-29 18:42 UTC, merged