Add code to AAD provider and REGO for 7.6 through 7.9 to support PIM for Groups
cisagov/ScubaGear pull request #945
Opened 2024-02-28 14:23 UTC by crutchfield

#  #
  

## 🗣 Description ##

Updated AAD Provider to add unified rules for PIM Groups associated with Privileged roles.  Updated AAD 7.6 - 7.9 to account for multiple rules (from directory role and from PIM Groups). 

closes #919 

TODO: #944  - Need to add new functional test cases.

## 💭 Motivation and context ##

PIM Groups provide mechanism to give users privileged access.  This enhancement allows to make sure notifications/alerts are produced appropriately. 

## 🧪 Testing ##

- Updated and ran REGO Unit test
- Ran ScubaGear on tenant with PIM Group - manually verified results. 

## ✅ Pre-approval checklist ##

- [X] This PR has an informative and human-readable title.
- [X] PR targets the correct parent branch (e.g., main or release-name) for merge.
- [X] Changes are limited to a single goal - *eschew scope creep!*
- [X] Changes are sized such that they do not touch excessive number of files.
- [X] *All* future TODOs are captured in issues, which are referenced in code comments.
- [X] These code changes follow the ScubaGear [content style guide](https://github.com/cisagov/ScubaGear/blob/main/CONTENTSTYLEGUIDE.md).
- [X] Related issues these changes resolve are linked preferably via [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).
- [X] All relevant type-of-change labels added.
- [X] All relevant project fields are set.
- [X] All relevant repo and/or project documentation updated to reflect these changes.
- [X] Unit tests added/updated to cover PowerShell and Rego changes.
- [X] Functional tests added/updated to cover PowerShell and Rego changes. Except covered in #944 
- [X] All relevant functional tests passed.
- [X] All automated checks (e.g., linting, static analysis, unit/smoke tests) passed.

## ✅ Pre-merge checklist ##

- [ ] PR passed smoke test check.
- [ ] Feature branch has been rebased against changes from parent branch, as needed

  Use `Rebase branch` button below or use [this](https://www.digitalocean.com/community/tutorials/how-to-rebase-and-update-a-pull-request) reference to rebase from the command line.
- [ ] Resolved all merge conflicts on branch
- [ ] Notified merge coordinator that PR is ready for merge via comment mention

## ✅ Post-merge checklist ##

- [ ] Feature branch deleted after merge to clean up repository.
- [ ] Verified that all checks pass on parent branch (e.g., main or release-name) after merge.

2024-03-01 22:17 UTC, ssatyapal123 reviewed
Initial test on E5 looks good:

1. Created a new PIM Group (Shanti Test PIM Group)
2. Assigned a privileged role (Cloud Application Administrator) to the Group
3. Added a user as an Eligible member of the new group
4. Ran ScubaGear on AAD
5. Checked the ProviderSettingsExport.Json for the privileged_users and privileged_roles objects
6. Verified that the new role was listed under the user within the privileged_users array
7. Noted that the user UUID was not listed within the privileged_roles array under the Cloud Application Administrator grouping (Question - should it be listed here or should this section only list users assigned directly to the role and not through the PIM Group?)
8. Added the same user with an active assignment to the Cloud Application Administrator role
9. Ran ScubaGear on AAD
10. Reviewed the ProviderSettingsExport.json
11. Verified that the user UUID was now listed under Cloud Application Administrator privileged_roles grouping

Next step is to test G5 tenants and determine other ways of verifying the test passed besides reviewing the provider JSON.

2024-03-06 19:19 UTC, tkol2022 requested changes
Update the message for 7.6 to say "0 role(s) or group(s) allowing **activation** without approval found" without the bold.

![image](https://github.com/cisagov/ScubaGear/assets/107076927/252ea2ec-15c2-426c-8211-1c7999a20dfa)

2024-03-06 23:07 UTC, tkol2022 commented
### Testing Strategy
To test this PR, I'm using the following setup and expected result scenarios to exercise the potential permutations of compliant and non-compliant states. Each scenario assumes that a specific PIM group used for the test is **actively** assigned to one or more highly privileged roles - in the case of 7.6 the group is assigned to Global Admin.

**Scenario 1 Pass** - Both the role configurations and the PIM group configurations are compliant with the policy.
**Scenario 2 Fail** - The role configuration is compliant but the group configuration is non-compliant.
**Scenario 3 Fail** - The group configuration is compliant but the role configuration is non-compliant
**Scenario 4 Fail** - Both the role and the group configurations are non-compliant.

2024-03-06 23:10 UTC, tkol2022 commented
### Test Results

| Policy | Test results |
|---|---|
| 7.6 Activation of the Global Administrator role SHALL require approval. | Tested all four scenarios and the report displayed the correct output. |
| 7.7 Eligible and Active highly privileged role assignments SHALL trigger an alert. | col2 |
| 7.8 User activation of the Global Administrator role SHALL trigger an alert. | col2 |
| 7.9 User activation of other highly privileged roles SHOULD trigger an alert. | col2 |

2024-03-07 00:20 UTC, tkol2022 commented
### Regression Testing Results
Modified the test configurations for policies 7.4 and 7.5.
Ran ScubaGear version 1.1.1 versus the code in this PR to compare the outputs for those policies.
Policies 7.4 and 7.5 produce the same output for both versions. This matches what I expected.

2024-03-07 00:26 UTC, tkol2022 commented
### Code review of JSON
I reviewed the new provider JSON structure and observed that now the PIM group configurations were added to the respective roles where groups are assigned. The new fields Rule.RuleSource, Rule.RuleSourceType were added and referenced in the Rego. No questions about these specific updates.

![image](https://github.com/cisagov/ScubaGear/assets/107076927/df8ebb31-f853-42e9-b896-10b3d35f665f)

2024-03-07 22:43 UTC, tkol2022 commented
> > Ran on G3 tenant and got the warning to terminal: "WARNING: Omitting calls to Get-PrivilegedRole and Get-PrivilegedUser."
> > The report showed "Error" in the Result column of the AAD-7 group policies. Wondering if there is a missing check to for tenants without the PIM capabilities.
> 
> can you post a screenshot? i will take a look
> 
> sure, here is a screenshot for G3:
> 
Shanti - Crutch is looking into why the code is giving errors for G3.

2024-03-07 22:45 UTC, tkol2022 commented on PowerShell/ScubaGear/Modules/Providers/ExportAADProvider.psm1
>      $PrivilegedRoles = [ScubaConfig]::ScubaDefault('DefaultPrivilegedRoles')
Crutch, can the config value for DefaultPrivilegedRoles be overridden by a custom config file created by the user?

2024-03-08 12:53 UTC, crutchfield commented
> Update the message for 7.6 to say "0 role(s) or group(s) allowing **activation** without approval found" without the bold.
> 
> ![image](https://private-user-images.githubusercontent.com/107076927/310633931-252ea2ec-15c2-426c-8211-1c7999a20dfa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5MDIzNjQsIm5iZiI6MTcwOTkwMjA2NCwicGF0aCI6Ii8xMDcwNzY5MjcvMzEwNjMzOTMxLTI1MmVhMmVjLTE1YzItNDI2Yy04MjExLTFjNzk5OWEyMGRmYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwOFQxMjQ3NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04OWZkNTAzZTQ1YTQ0OGJiYjY4OWU2MGNlMDY2Zjg5YzMxOTAxZjA0ZmM0OTQwNGMxYjQ4OThhNzZhNTY1NGNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.s8_tbngA9Ew-rRyv2JmaXwzfcP_J_Yo2uduN_9sjft0)

Inserted activation in details

2024-03-08 13:52 UTC, crutchfield commented
> > > Ran on G3 tenant and got the warning to terminal: "WARNING: Omitting calls to Get-PrivilegedRole and Get-PrivilegedUser."
> > > The report showed "Error" in the Result column of the AAD-7 group policies. Wondering if there is a missing check to for tenants without the PIM capabilities.
> > 
> > 
> > can you post a screenshot? i will take a look
> > sure, here is a screenshot for G3:
> 
> Shanti - Crutch is looking into why the code is giving errors for G3.

Issue is directly related to expired license.  When retrieving Service Plans we check for provisioning status of 'Success'. In our case it is 'Disabled' since the license has expired.  Question is how to handle as was ask in another thread.  I believe this is out of scope of this issue.   

> > > Ran on G3 tenant and got the warning to terminal: "WARNING: Omitting calls to Get-PrivilegedRole and Get-PrivilegedUser."
> > > The report showed "Error" in the Result column of the AAD-7 group policies. Wondering if there is a missing check to for tenants without the PIM capabilities.
> > 
> > 
> > can you post a screenshot? i will take a look
> > sure, here is a screenshot for G3:
> 
> Shanti - Crutch is looking into why the code is giving errors for G3.

This is directly related to expired license.  We look for service plans with a provisioning status of 'Success'.  In this case it is 'Disabled'.  The code then indicate getting privileged roles & users will be omitted.  This begs the previously ask question, do we alert the user that the service plans are disabled?  I believe resolution is out of scope of this issue.  WIll open another issue to track.

2024-03-08 16:02 UTC, ssatyapal123 approved these changes
Ran against GCC High and verified results were as expected:

![image](https://github.com/cisagov/ScubaGear/assets/78565245/512a4d84-ebbe-4ee9-afaa-e8df5556811a)

Also ran on E5, and verified results. Ran a scenario for 7.7 and verified that a role with a PIM assignment that was previously failing subsequently passed as expected.

2024-03-08 17:38 UTC, crutchfield commented
@tkol2022  Added code to cache check for PIM Groups Looks like a good number of hits. With a large number of assignments the hit/miss ration would just get better.

2024-03-11 21:21 UTC, crutchfield commented on PowerShell/ScubaGear/Modules/Providers/ExportAADProvider.psm1
> +        ($GroupEligibilitySchedule = Get-MgBetaIdentityGovernancePrivilegedAccessGroupEligibilitySchedule -Filter "groupId eq '$PrincipalId'") *> $null
```suggestion
        ($GroupEligibilitySchedule = Get-MgBetaIdentityGovernancePrivilegedAccessGroupEligibilitySchedule -Filter "groupId eq '$GroupId'") *> $null
```

2024-03-11 21:23 UTC, crutchfield commented
@tkol2022 I fixed IsPimGroup per our discussion

2024-03-13 11:07 UTC, crutchfield commented
@tkol2022 Update caching to use privileged users functions determination of an Id as a user (i.e. non-group) to reduce future API calls in privileged role, in particular PIM Groups,  Also cleared cache after processing so would be clean if executed again.

2024-03-19 01:10 UTC, tkol2022 commented
This is blocked waiting the reactivation of the G3 tenant.

2024-03-19 13:25 UTC, tkol2022 approved these changes

2024-03-19 17:42 UTC, tkol2022 commented
@nanda-katikaneni ready for merge

2024-03-19 19:26 UTC, merged